packages:
  - "apps/*"
  - "packages/*"

# Allow lifecycle scripts for packages that need to build native binaries
# Required for pnpm v10+ which blocks scripts by default
onlyBuiltDependencies:
  - sharp
  - esbuild
  - prisma
  - "@prisma/client"
  - "@prisma/engines"
