// Integration-harness Prisma client backed by the Boolean-`emailVerified` test client (generated by
// gen-boolean-client.mjs). The integration vitest config aliases the bare `@formbricks/database`
// specifier to this module so the REAL Better Auth instance + hooks create/read Users against a
// client whose `emailVerified` is Boolean and `Account.type` is optional — the POST-CUTOVER shape BA
// uses. The live DateTime schema, the generated client, and the unit harness are all untouched.
//
// Only the bare specifier is aliased: `@formbricks/database/prisma` (the enums + Prisma namespace) is
// schema-agnostic at runtime and resolves normally.
//
// Constructed from the same options as the app's client (packages/database/src/client.ts), so what a
// read returns here is what a read returns in production — the global `omit`, the transaction budgets
// and the pool's session settings included.
import { PrismaClient } from "../../../packages/database/generated/prisma-test/client";
import { createAppPrismaClientOptions } from "../../../packages/database/src/client-options";

export const prisma = new PrismaClient(createAppPrismaClientOptions());
