apiVersion: v2
name: formbricks
description: A Helm chart for Formbricks with PostgreSQL, Redis, Traefik, and cert-manager
type: application
version: 0.1.1
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 15.5.36
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 20.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: nginx
    version: 18.2.3
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
  - name: cert-manager
    version: v1.16.1
    repository: https://charts.jetstack.io
    condition: certmanager.enabled
