{{- if and (.Values.secret) (.Values.secret.enabled) }}
{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "formbricks.name" $ }}-postgres
  labels:
    {{- include "formbricks.labels" $ | nindent 4 }}
data:
  POSTGRES_ADMIN_PASSWORD: {{ include "formbricks.postgresAdminPassword" . | b64enc }}
  POSTGRES_USER_PASSWORD: {{ include "formbricks.postgresUserPassword" . | b64enc }}
{{- end }}
{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "formbricks.name" $ }}-redis
  labels:
    {{- include "formbricks.labels" $ | nindent 4 }}
data:
  REDIS_PASSWORD: {{ include "formbricks.redisPassword" . | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "formbricks.name" $ }}-app-secrets
  labels:
    {{- include "formbricks.labels" $ | nindent 4 }}
data:
  {{- if .Values.redis.enabled }}
  REDIS_URL: {{ printf "redis://:%s@formbricks-redis-master:6379" (include "formbricks.redisPassword" .) | b64enc }}
    {{- else }}
  REDIS_URL: {{ .Values.redis.externalRedisUrl | b64enc }}
    {{- end }}
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ printf "postgresql://formbricks:%s@formbricks-postgresql/formbricks" (include "formbricks.postgresUserPassword" .) | b64enc }}
  {{- else }}
  DATABASE_URL: {{ .Values.postgresql.externalDatabaseUrl | b64enc }}
  {{- end }}
  CRON_SECRET: {{ include "formbricks.cronSecret" . | b64enc }}
  ENCRYPTION_KEY: {{ include "formbricks.encryptionKey" . | b64enc }}
  NEXTAUTH_SECRET: {{ include "formbricks.nextAuthSecret" . | b64enc }}
{{- end }}