services:
  postgres:
    image: pgvector/pgvector:pg17
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  mailhog:
    image: arjenz/mailhog # Copy of mailhog/MailHog to support linux/arm64
    ports:
      - 8025:8025 # web ui
      - 1025:1025 # smtp server

volumes:
  postgres:
    driver: local
