import library from "@formbricks/config-eslint/library";

// The library tier (eslint + typescript-eslint recommendedTypeChecked) does not enable `no-console`,
// so the CLI/migration scripts here that log intentionally need no package-wide override.
export default [
  ...library({ tsconfigRootDir: import.meta.dirname }),
  {
    // Prisma client output (root .gitignore: `packages/database/generated`), regenerated by
    // `pnpm generate` and absent on a fresh clone. Root-anchored on purpose: a nested
    // `foo/generated/` anywhere else in this package still gets linted.
    ignores: ["generated/**"],
  },
  {
    files: ["migration/**"],
    // `reportUnusedDisableDirectives` is fixable, so with it on, `pnpm lint:fix` (`eslint . --fix`)
    // rewrites any shipped migration whose disable directives a config change has since made
    // redundant — deleting comments from a file that has already run, which is exactly what the
    // grandfathering below exists to prevent. Off for the whole directory rather than one file:
    // every migration in here is frozen once it ships, so none of them should ever be rewritten
    // by an autofix, and a stale directive in one is not something we would act on anyway.
    linterOptions: { reportUnusedDisableDirectives: "off" },
    rules: {
      // `while (true) { ... break }` is the batch-drain idiom these data migrations use to page
      // through a table. `only-allowed-literals` exempts a loop test that is literally
      // `true`/`false`/`1`/`0` and nothing else, so a computed always-truthy condition —
      // `while (someObject)`, the bug this rule exists to catch — is still an error. Scoped to
      // `migration/` rather than the shared tier because no other package writes drain loops,
      // and set here rather than per site so future migrations don't each carry a disable.
      "@typescript-eslint/no-unnecessary-condition": [
        "error",
        { allowConstantLoopConditions: "only-allowed-literals" },
      ],
    },
  },
  /*
   * Grandfathered applied migrations.
   *
   * A data migration that has already run is frozen history: the file here is meant to be what
   * actually executed. Editing one to satisfy a lint rule changes the migration only for installs
   * that have not reached it yet, so two populations end up having run different code — a poor
   * trade for lint hygiene. These files are therefore exempted rather than fixed, each from only
   * the rules it actually violates, so a *new* violation of any other rule still fails.
   *
   * For the same reason, `20241209104738_xm_user_identification/migration.ts` keeps its two
   * file-level disables even though the loop option above has made both redundant: deleting them
   * would be an edit to a shipped migration. The `linterOptions` above is what stops `lint:fix`
   * from deleting them for us.
   *
   * Do not add entries. A migration that has not shipped yet should be fixed instead.
   */
  {
    files: ["migration/20250326111101_move_api_keys_to_api_keys_new/migration.ts"],
    rules: {
      // Two bare `@ts-expect-error`s over an untyped `$queryRaw`, and the error-typed row
      // accesses that follow from it.
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
    },
  },
  {
    files: ["migration/20260119123112_migrate_legacy_validation_to_rules/utils.ts"],
    rules: {
      // Guards against legacy `Survey.blocks` JSON that the hand-written `SurveyElement` type
      // describes more optimistically than the stored data — the rule reads them as dead.
      "@typescript-eslint/no-unnecessary-condition": "off",
    },
  },
  {
    rules: {
      // Runtime-only env read: the ENG-2343 data migration derives the deployment's MCP resource
      // identifier from WEBAPP_URL when it runs, which is not a build input, so declaring it in
      // turbo.json would only add it to the build hash for nothing. Same reasoning as packages/logger.
      "turbo/no-undeclared-env-vars": ["error", { allowList: ["WEBAPP_URL"] }],
    },
  },
];
