name: Bug report
description: "Found a bug? Please fill out the sections below. \U0001F44D"
title: "[BUG]"
labels: bug
assignees: []
body:
- type: textarea
  id: issue-summary
  attributes:
    label: Issue Summary
    description: A summary of the issue. This needs to be a clear detailed-rich summary.
  validations:
    required: true
- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to Reproduce
    value: |
      1. (for example) Went to ...
      2. Clicked on...
      3. ...
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  id: other-information
  attributes:
    label: Other information
  validations:
    required: false
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
  validations:
    required: false
- type: textarea
  id: environment
  attributes:
    label: Environment
    value: |
      - [ ] Formbricks Cloud (app.formbricks.com)
      - [ ] self-hosted Formbricks, version/commit: [please provide]
  validations:
    required: true
- type: markdown
  id: desktop-version
  attributes:
    value: | 
      #### Desktop (please complete the following information):

      - OS: [e.g. iOS]
      - Browser [e.g. chrome, safari]
      - Version [e.g. 22]
- type: markdown
  id: nodejs-version
  attributes:
    value: | 
      #### Node.JS version
      
      [e.g. v18.15.0] 
- type: markdown
  id: anything-else
  attributes:
    value: |
      #### Anything else?
      
      - Screen recording, console logs, network requests: You can make a recording with [Loom](https://www.loom.com).
      - Anything else that you think could be an issue?
