name: Bug report
description: "Found a bug? Please fill out the sections below. \U0001F44D"
title: ""
labels: bug
assignees: []
body:
  - type: textarea
    id: issue-summary
    attributes:
      label: Issue Summary
      description: A summary of the issue. This needs to be a clear detailed-rich summary.
    validations:
      required: true
    validations:
      required: true
  - type: textarea
    id: other-information
    attributes:
      label: Other information (incl. screenshots, Formbricks version, steps to reproduce,...)
    validations:
      required: false
  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      options:
        - label: Formbricks Cloud (app.formbricks.com)
        - label: Self-hosted Formbricks
