import { toDesiredEmbeddedFields } from "@formbricks/types/embedded-data-mapping";
import type { TSurveyHiddenFields, TSurveyVariables } from "@formbricks/types/surveys/types";

/** One survey's legacy declarations, as read from the database. */
export interface TLegacySurveyRow {
  id: string;
  workspaceId: string;
  variables: TSurveyVariables;
  hiddenFields: TSurveyHiddenFields;
}

/**
 * An `EmbeddedData` row to insert. `key` and `locked` are left to the column defaults — a migrated
 * field is local (no library key) and unlocked (nothing could refuse an outside write before this).
 */
export interface TEmbeddedDataInsert {
  id: string;
  workspaceId: string;
  surveyId: string;
  name: string;
  source: "computed" | "ingested";
  dataType: "string" | "number" | "boolean" | "date";
  defaultValue: string | number | boolean | null;
}

export interface TSurveyEmbeddedDataInsert {
  id: string;
  workspaceId: string;
  surveyId: string;
  embeddedDataId: string;
  storageKey: string;
}

export type TSurveyBackfillPlan =
  | { status: "ok"; fields: TEmbeddedDataInsert[]; links: TSurveyEmbeddedDataInsert[] }
  | { status: "skipped"; duplicateStorageKeys: string[] };

/**
 * Works out the rows and links one survey needs, or reports that it can't be migrated.
 *
 * The §8 mapping itself lives in `toDesiredEmbeddedFields`, shared with the ENG-1978 write bridge
 * and the ENG-1836 read seam — the two invariants that keep a migrated survey resolving (a
 * variable's `storageKey` is its original cuid, a hidden field's is its original name) are stated
 * once, there.
 *
 * What this adds is the one thing a bulk migration has to handle and a single-survey save does not:
 * **a survey whose declarations already collide.** `@@unique([surveyId, storageKey])` would reject
 * such a pair, and because the runner wraps every data migration in one transaction, a single bad
 * survey would roll back the entire backfill. Reporting it lets the caller skip that survey and
 * migrate the rest. `toDesiredEmbeddedFields` passes duplicates through rather than merging them
 * precisely so this decision belongs here.
 *
 * Ids are generated by the caller rather than left to the column default, so the links can be built
 * in the same pass and both tables written with a plain `createMany`.
 */
export const planSurveyBackfill = (survey: TLegacySurveyRow, newId: () => string): TSurveyBackfillPlan => {
  const desired = toDesiredEmbeddedFields(survey);

  const seen = new Set<string>();
  const duplicateStorageKeys = new Set<string>();
  for (const field of desired) {
    if (seen.has(field.storageKey)) duplicateStorageKeys.add(field.storageKey);
    seen.add(field.storageKey);
  }
  if (duplicateStorageKeys.size > 0) {
    return { status: "skipped", duplicateStorageKeys: [...duplicateStorageKeys] };
  }

  const fields: TEmbeddedDataInsert[] = [];
  const links: TSurveyEmbeddedDataInsert[] = [];

  for (const desiredField of desired) {
    const embeddedDataId = newId();
    fields.push({
      id: embeddedDataId,
      workspaceId: survey.workspaceId,
      surveyId: survey.id,
      name: desiredField.name,
      // `reserved` is never a stored row, and `toDesiredEmbeddedFields` never produces one.
      source: desiredField.source === "computed" ? "computed" : "ingested",
      dataType: desiredField.dataType,
      defaultValue: desiredField.defaultValue,
    });
    links.push({
      id: newId(),
      workspaceId: survey.workspaceId,
      surveyId: survey.id,
      embeddedDataId,
      storageKey: desiredField.storageKey,
    });
  }

  return { status: "ok", fields, links };
};
