{{- if (.Values.externalSecret).enabled }}
{{- range $nameSuffix, $data := .Values.externalSecret.files }}
{{- $target := default (dict) $data.target }}
{{- $targetTemplate := default (dict) $target.template }}
{{- $targetMetadata := default (dict) $targetTemplate.metadata }}
{{- $defaultTargetName := printf "%s-%s" (include "formbricks.name" $) $nameSuffix }}
{{- $targetName := default $defaultTargetName $target.name }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "formbricks.name" $ }}-{{ $nameSuffix }}
  labels:
  {{- include "formbricks.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: {{ $.Values.externalSecret.refreshInterval }}
{{- if and (not $data.data) (not $data.dataFrom) }}
{{- fail "Data or datafrom not specified for secret {{ template 'formbricks.name' $ }}-{{ $nameSuffix }} " }}
{{- end }}
{{- if $data.data }}
  data:
{{- range $secretKey, $remoteRef := $data.data }}
    - secretKey: {{ $secretKey }}
{{ toYaml $remoteRef | indent 6 }}
{{- end }}
{{- end }}
{{- if $data.dataFrom }}
  dataFrom:
    - extract:
{{ toYaml $data.dataFrom | indent 8 }}
{{- end }}
  {{- if $data.secretStore }}
  secretStoreRef:
    name: {{ $data.secretStore.name }}
    kind: {{ $data.secretStore.kind | default "SecretStore" }}
  {{- else }}
  secretStoreRef:
    name: {{ $.Values.externalSecret.secretStore.name }}
    kind: {{ $.Values.externalSecret.secretStore.kind | default "SecretStore" }}
  {{- end }}
  target:
    name: {{ $targetName }}
    template:
      type: {{ coalesce $targetTemplate.type $data.type "Opaque" }}
{{- if $targetTemplate.engineVersion }}
      engineVersion: {{ $targetTemplate.engineVersion }}
{{- end }}
{{- if $targetTemplate.mergePolicy }}
      mergePolicy: {{ $targetTemplate.mergePolicy }}
{{- end }}
{{- if or $data.annotations $data.labels $targetMetadata.annotations $targetMetadata.labels }}
      metadata:
{{- if or $data.annotations $targetMetadata.annotations }}
        annotations:
{{- if $data.annotations }}
{{ toYaml $data.annotations | indent 10 }}
{{- end }}
{{- if $targetMetadata.annotations }}
{{ toYaml $targetMetadata.annotations | indent 10 }}
{{- end }}
{{- end }}
{{- if or $data.labels $targetMetadata.labels }}
        labels:
{{- if $data.labels }}
{{ toYaml $data.labels | indent 10 }}
{{- end }}
{{- if $targetMetadata.labels }}
{{ toYaml $targetMetadata.labels | indent 10 }}
{{- end }}
{{- end }}
{{- end }}
{{- if $targetTemplate.data }}
      data:
{{ toYaml $targetTemplate.data | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
