{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "formbricks.redisName" . }}-configuration
  labels:
    helm.sh/chart: {{ include "formbricks.chart" . }}
    app.kubernetes.io/name: {{ include "formbricks.redisName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Values.partOfOverride | default (include "formbricks.name" .) }}
data:
  valkey.conf: |-
{{ .Values.redis.commonConfiguration | nindent 4 }}
{{- end }}
