import type { TWorkflowDefinition } from "../types/document";
import { type TWorkflowTriggerRunPayload, ZWorkflowTriggerRunPayload } from "../types/runs";
import { WORKFLOW_TRIGGERS } from "../types/triggers/enum";
import type { TResponseCompletedTriggerConfig } from "../types/triggers/response-completed";

/**
 * Pure builder for the trigger payload of a dry-run (test) WorkflowRun.
 *
 * A dry run executes the workflow exactly like a real `response.completed` run; only the *source*
 * of the trigger data differs — an existing response replayed as sample data, or a synthesized
 * sample. Both paths funnel through {@link buildDryRunTriggerPayload} so the payload shape is
 * identical to a live run and is validated against the contract schema before any run row exists.
 *
 * This module is intentionally dependency-free (no Prisma, no survey/response access): the adapter
 * (`apps/web`) fetches the survey/response and supplies the resolved {@link DryRunTriggerSource},
 * keeping the package a framework-agnostic leaf.
 */

/**
 * The `response.completed` trigger config of a workflow definition.
 *
 * `response.completed` is currently the only trigger type, so this is a typed accessor. When a
 * second trigger type is added, `definition.trigger` becomes a union and this return type stops
 * matching — a compile error that forces the caller to narrow on `triggerType` then.
 */
export const getResponseCompletedTriggerConfig = (
  definition: TWorkflowDefinition
): TResponseCompletedTriggerConfig => definition.trigger.config;

/**
 * The ending card a synthesized dry run should claim was reached.
 *
 * The trigger config lists the endings that fire the workflow; an empty list means "any ending".
 * When specific endings are configured we use the first, so the synthesized payload always
 * satisfies the trigger's own ending filter; with no configured endings we leave it undefined.
 */
export const selectSampleEndingCardId = (trigger: TResponseCompletedTriggerConfig): string | undefined =>
  trigger.endingCardIds[0];

/** Resolved trigger data for a dry run — either replayed from a real response or synthesized. */
export interface DryRunTriggerSource {
  /** A replayed response's id, or a sample id generated by the adapter for a synthesized run. */
  responseId: string;
  /** Ending card the response reached. Omit for "unspecified / any ending". */
  endingCardId?: string;
  /** Response data exposed to the workflow (answers, variables, hidden fields). */
  data?: Record<string, unknown>;
}

/**
 * Assemble and validate the trigger payload stored on a dry-run WorkflowRun. Validating here means
 * a malformed payload fails before a run row is created, rather than at execution time.
 */
export const buildDryRunTriggerPayload = ({
  workspaceId,
  trigger,
  source,
  triggeredAt,
}: {
  workspaceId: string;
  trigger: TResponseCompletedTriggerConfig;
  source: DryRunTriggerSource;
  /** ISO-8601 timestamp (with offset) the adapter stamps; passed in to keep this builder pure. */
  triggeredAt: string;
}): TWorkflowTriggerRunPayload =>
  ZWorkflowTriggerRunPayload.parse({
    type: WORKFLOW_TRIGGERS.RESPONSE_COMPLETED,
    workspaceId,
    surveyId: trigger.surveyId,
    responseId: source.responseId,
    ...(source.endingCardId !== undefined ? { endingCardId: source.endingCardId } : {}),
    ...(source.data !== undefined ? { data: source.data } : {}),
    triggeredAt,
  });
