export const CLOUD_PRICING_DATA = {
  plans: [
    {
      name: "Free",
      id: "free",
      featured: false,
      description: "Unlimited Surveys, Team Members, and more.",
      price: { monthly: "$0", yearly: "$0" },
      mainFeatures: [
        "Unlimited Surveys",
        "Unlimited Team Members",
        "1,500 Monthly Responses",
        "2,000 Monthly Identified Users",
        "Website Surveys",
        "App Surveys",
        "Unlimited Apps & Websites",
        "Link Surveys (Shareable)",
        "Email Embedded Surveys",
        "Logic Jumps, Hidden Fields, Recurring Surveys, etc.",
        "API & Webhooks",
        "All Integrations",
        "All surveying features",
      ],
      href: "https://app.formbricks.com/auth/signup?plan=free",
    },
    {
      name: "Startup",
      id: "startup",
      featured: false,
      description: "Everything in Free with additional features.",
      price: { monthly: "$39", yearly: "$390 " },
      mainFeatures: [
        "Everything in Free",
        "Remove Branding",
        "Email Support",
        "5,000 Monthly Responses",
        "7,500 Monthly Identified Users",
      ],
      href: "https://app.formbricks.com/auth/signup?plan=startup",
    },
    {
      name: "Scale",
      id: "scale",
      featured: true,
      description: "Advanced features for scaling your business.",
      price: { monthly: "$149", yearly: "$1,490" },
      mainFeatures: [
        "Everything in Startup",
        "Team Access Roles",
        "Multi-Language Surveys",
        "Advanced Targeting",
        "Priority Support",
        "10,000 Monthly Responses",
        "30,000 Monthly Identified Users",
      ],
      href: "https://app.formbricks.com/auth/signup?plan=scale",
    },
    {
      name: "Enterprise",
      id: "enterprise",
      featured: false,
      description: "Premium support and custom limits.",
      price: { monthly: "Say Hi!", yearly: "Say Hi!" },
      mainFeatures: [
        "Everything in Scale",
        "Custom MIU limit",
        "Premium support with SLAs",
        "Uptime SLA (99%)",
        "Customer Success Manager",
        "Technical Onboarding",
      ],
      href: "https://cal.com/johannes/enterprise-cloud",
    },
  ],
};
