{{- if and (.Values.secret) (.Values.secret.enabled) }}

{{- $postgresAdminPassword := include "formbricks.postgresAdminPassword" . }}
{{- $postgresUserPassword := include "formbricks.postgresUserPassword" . }}
{{- $redisPassword := include "formbricks.redisPassword" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "formbricks.name" . }}-app-secrets
  labels:
    {{- include "formbricks.labels" . | nindent 4 }}
data:
  {{- if .Values.redis.enabled }}
  REDIS_URL: {{ printf "redis://default:%s@formbricks-redis-master:6379" $redisPassword | b64enc }}
  {{- else }}
  REDIS_URL: {{ .Values.redis.externalRedisUrl | b64enc }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ printf "postgresql://formbricks:%s@formbricks-postgresql/formbricks" $postgresUserPassword | b64enc }}
  {{- else }}
  DATABASE_URL: {{ .Values.postgresql.externalDatabaseUrl | b64enc }}
  {{- end }}
  CRON_SECRET: {{ include "formbricks.cronSecret" . | b64enc }}
  ENCRYPTION_KEY: {{ include "formbricks.encryptionKey" . | b64enc }}
  NEXTAUTH_SECRET: {{ include "formbricks.nextAuthSecret" . | b64enc }}
  {{- if and (.Values.enterprise.licenseKey) (ne .Values.enterprise.licenseKey "") }}
  ENTERPRISE_LICENSE_KEY: {{ .Values.enterprise.licenseKey | b64enc }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  redis-password: {{ $redisPassword | b64enc }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_ADMIN_PASSWORD: {{ $postgresAdminPassword | b64enc }}
  POSTGRES_USER_PASSWORD: {{ $postgresUserPassword | b64enc }}
  {{- end }}
  {{- if .Values.minio.enabled }}

  {{- end }}
{{- end }}
