import { TFunction } from "i18next";
import { TSurvey } from "@formbricks/types/surveys/types";
import { getDefaultEndingCard, getDefaultWelcomeCard } from "@/app/lib/survey-builder";

export const getMinimalSurvey = (t: TFunction): TSurvey => ({
  id: "someUniqueId1",
  createdAt: new Date(),
  updatedAt: new Date(),
  name: "Minimal Survey",
  type: "app",
  workspaceId: "someWorkspaceId1",
  createdBy: null,
  status: "draft",
  publishOn: null,
  closeOn: null,
  displayOption: "displayOnce",
  autoClose: null,
  triggers: [],
  recontactDays: null,
  displayLimit: null,
  welcomeCard: getDefaultWelcomeCard(t),
  questions: [],
  blocks: [],
  endings: [getDefaultEndingCard([], t)],
  hiddenFields: {
    enabled: false,
  },
  delay: 0, // No delay
  displayPercentage: null,
  autoComplete: null,
  surveyClosedMessage: {
    enabled: false,
  },
  workspaceOverwrites: null,
  recaptcha: null,
  singleUse: null,
  styling: null,
  segment: null,
  languages: [],
  showLanguageSwitch: false,
  autoSelectLanguage: false,
  isVerifyEmailEnabled: false,
  isSingleResponsePerEmailEnabled: false,
  variables: [],
  followUps: [],
  isBackButtonHidden: false,
  isAutoProgressingEnabled: true,
  metadata: {},
  slug: null,
  isCaptureIpEnabled: false,
});
