
















































};  },    },      },        },          schema: makePartialSchema(z.any()), // Replace with actual schema        "application/json": {      content: {      description: "Project team created successfully.",    "201": {  responses: {  },    },      },        schema: TProjectTeamInput,      "application/json": {    content: {    required: true,  requestBody: {  tags: ["Organizations API > Project Teams"],  description: "Creates a project team in the given organization.",  summary: "Create a project team",  operationId: "createProjectTeam",export const createProjectTeamEndpoint: ZodOpenApiOperationObject = {};  },    },      },        },          schema: z.array(makePartialSchema(z.any())), // Replace with actual schema        "application/json": {      content: {      description: "Project teams retrieved successfully.",    "200": {  responses: {  },    query: TGetProjectTeamsFilter.sourceType().required(),  requestParams: {  tags: ["Organizations API > Project Teams"],  description: "Retrieve a list of project teams for the given organization.",  summary: "Retrieve project teams",  operationId: "getProjectTeams",export const getProjectTeamsEndpoint: ZodOpenApiOperationObject = {import { makePartialSchema } from "@/modules/api/v2/types/openapi-response";import { z } from "zod";import { TGetProjectTeamsFilter, TProjectTeamInput } from "../types/projectTeams";import { ZodOpenApiOperationObject } from "zod-openapi";