import { createId } from "@paralleldrive/cuid2";

import {
  TSurvey,
  TSurveyHiddenFields,
  TSurveyOpenTextQuestion,
  TSurveyQuestionType,
} from "@formbricks/types/surveys";
import { TTemplate } from "@formbricks/types/templates";

const thankYouCardDefault = {
  enabled: true,
  headline: { en: "Thank you!" },
  subheader: { en: "We appreciate your feedback." },
  buttonLabel: "Create your own Survey",
  buttonLink: "https://formbricks.com/signup",
};

const hiddenFieldsDefault: TSurveyHiddenFields = {
  enabled: true,
  fieldIds: [],
};

const welcomeCardDefault = {
  enabled: false,
  headline: { en: "Welcome!" },
  html: { en: "Thanks for providing your feedback - let's go!" },
  timeToFinish: false,
  showResponseCount: false,
};

export const testTemplate: TTemplate = {
  name: "Test template",
  description: "Test template consisting of all questions",
  preset: {
    name: "Test template",
    questions: [
      {
        id: createId(),
        type: TSurveyQuestionType.OpenText,
        headline: { en: "This is an open text question" },
        subheader: { en: "Please enter some text:" },
        required: true,
        inputType: "text",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.OpenText,
        headline: { en: "This is an open text question" },
        subheader: { en: "Please enter some text:" },
        required: false,
        inputType: "text",
      },

      {
        id: createId(),
        type: TSurveyQuestionType.OpenText,
        headline: { en: "This is an open text question" },
        subheader: { en: "Please enter an email" },
        required: true,
        inputType: "email",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.OpenText,
        headline: { en: "This is an open text question" },
        subheader: { en: "Please enter an email" },
        required: false,
        inputType: "email",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.OpenText,
        headline: { en: "This is an open text question" },
        subheader: { en: "Please enter a number" },
        required: true,
        inputType: "number",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.OpenText,
        headline: { en: "This is an open text question" },
        subheader: { en: "Please enter a number" },
        required: false,
        inputType: "number",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.OpenText,
        headline: { en: "This is an open text question" },
        subheader: { en: "Please enter a phone number" },
        required: true,
        inputType: "phone",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.OpenText,
        headline: { en: "This is an open text question" },
        subheader: { en: "Please enter a phone number" },
        required: false,
        inputType: "phone",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.OpenText,
        headline: { en: "This is an open text question" },
        subheader: { en: "Please enter a url" },
        required: true,
        inputType: "url",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.OpenText,
        headline: { en: "This is an open text question" },
        subheader: { en: "Please enter a url" },
        required: false,
        inputType: "url",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.MultipleChoiceSingle,
        headline: { en: "This ia a Multiple choice Single question" },
        subheader: { en: "Please select one of the following" },
        required: true,
        shuffleOption: "none",
        choices: [
          {
            id: createId(),
            label: { en: "Option1" },
          },
          {
            id: createId(),
            label: { en: "Option2" },
          },
        ],
      },
      {
        id: createId(),
        type: TSurveyQuestionType.MultipleChoiceSingle,
        headline: { en: "This ia a Multiple choice Single question" },
        subheader: { en: "Please select one of the following" },
        required: false,
        shuffleOption: "none",
        choices: [
          {
            id: createId(),
            label: { en: "Option 1" },
          },
          {
            id: createId(),
            label: { en: "Option 2" },
          },
        ],
      },
      {
        id: createId(),
        type: TSurveyQuestionType.MultipleChoiceMulti,
        headline: { en: "This ia a Multiple choice Multiple question" },
        subheader: { en: "Please select some from the following" },
        required: true,
        shuffleOption: "none",
        choices: [
          {
            id: createId(),
            label: { en: "Option1" },
          },
          {
            id: createId(),
            label: { en: "Option2" },
          },
        ],
      },
      {
        id: createId(),
        type: TSurveyQuestionType.MultipleChoiceMulti,
        headline: { en: "This ia a Multiple choice Multiple question" },
        subheader: { en: "Please select some from the following" },
        required: false,
        shuffleOption: "none",
        choices: [
          {
            id: createId(),
            label: { en: "Option1" },
          },
          {
            id: createId(),
            label: { en: "Option2" },
          },
        ],
      },
      {
        id: createId(),
        type: TSurveyQuestionType.Rating,
        headline: { en: "This is a rating question" },
        required: true,
        lowerLabel: { en: "Low" },
        upperLabel: { en: "High" },
        range: 5,
        scale: "number",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.Rating,
        headline: { en: "This is a rating question" },
        required: false,
        lowerLabel: { en: "Low" },
        upperLabel: { en: "High" },
        range: 5,
        scale: "number",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.Rating,
        headline: { en: "This is a rating question" },
        required: true,
        lowerLabel: { en: "Low" },
        upperLabel: { en: "High" },
        range: 5,
        scale: "smiley",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.Rating,
        headline: { en: "This is a rating question" },
        required: false,
        lowerLabel: { en: "Low" },
        upperLabel: { en: "High" },
        range: 5,
        scale: "smiley",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.Rating,
        headline: { en: "This is a rating question" },
        required: true,
        lowerLabel: { en: "Low" },
        upperLabel: { en: "High" },
        range: 5,
        scale: "star",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.Rating,
        headline: { en: "This is a rating question" },
        required: false,
        lowerLabel: { en: "Low" },
        upperLabel: { en: "High" },
        range: 5,
        scale: "star",
      },

      {
        id: createId(),
        type: TSurveyQuestionType.CTA,
        headline: { en: "This is a CTA question" },
        html: { en: "This is a test CTA" },
        buttonLabel: { en: "Click" },
        buttonUrl: "https://formbricks.com",
        buttonExternal: true,
        required: true,
        dismissButtonLabel: { en: "Maybe later" },
      },
      {
        id: createId(),
        type: TSurveyQuestionType.CTA,
        headline: { en: "This is a CTA question" },
        html: { en: "This is a test CTA" },
        buttonLabel: { en: "Click" },
        buttonUrl: "https://formbricks.com",
        buttonExternal: true,
        required: false,
        dismissButtonLabel: { en: "Maybe later" },
      },
      {
        id: createId(),
        type: TSurveyQuestionType.PictureSelection,
        headline: { en: "This is a Picture select" },
        allowMulti: true,
        required: true,
        choices: [
          {
            id: createId(),
            imageUrl: "https://formbricks-cdn.s3.eu-central-1.amazonaws.com/puppy-1-small.jpg",
          },
          {
            id: createId(),
            imageUrl: "https://formbricks-cdn.s3.eu-central-1.amazonaws.com/puppy-2-small.jpg",
          },
        ],
      },
      {
        id: createId(),
        type: TSurveyQuestionType.PictureSelection,
        headline: { en: "This is a Picture select" },
        allowMulti: true,
        required: false,
        choices: [
          {
            id: createId(),
            imageUrl: "https://formbricks-cdn.s3.eu-central-1.amazonaws.com/puppy-1-small.jpg",
          },
          {
            id: createId(),
            imageUrl: "https://formbricks-cdn.s3.eu-central-1.amazonaws.com/puppy-2-small.jpg",
          },
        ],
      },
      {
        id: createId(),
        type: TSurveyQuestionType.Consent,
        headline: { en: "This is a Consent question" },
        required: true,
        label: { en: "I agree to the terms and conditions" },
        dismissButtonLabel: "Skip",
      },
      {
        id: createId(),
        type: TSurveyQuestionType.Consent,
        headline: { en: "This is a Consent question" },
        required: false,
        label: { en: "I agree to the terms and conditions" },
        dismissButtonLabel: "Skip",
      },
    ],
    thankYouCard: thankYouCardDefault,
    welcomeCard: welcomeCardDefault,
    hiddenFields: {
      enabled: false,
    },
  },
};

export const templates: TTemplate[] = [
  {
    name: "Product Market Fit (Superhuman)",
    category: "Product Experience",

    description: "Measure PMF by assessing how disappointed users would be if your product disappeared.",
    preset: {
      name: "Product Market Fit (Superhuman)",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          html: {
            en: '<p class="fb-editor-paragraph" dir="ltr"><span>We would love to understand your user experience better. Sharing your insight helps a lot!</span></p>',
          },
          type: TSurveyQuestionType.CTA,
          logic: [{ condition: "skipped", destination: "end" }],
          headline: { en: "You are one of our power users! Do you have 5 minutes?" },
          required: false,
          buttonLabel: { en: "Happy to help!" },
          buttonExternal: false,
          dismissButtonLabel: { en: "No, thanks." },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "How disappointed would you be if you could no longer use {{productName}}?" },
          subheader: { en: "Please select one of the following options:" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "Not at all disappointed" },
            },
            {
              id: createId(),
              label: { en: "Somewhat disappointed" },
            },
            {
              id: createId(),
              label: { en: "Very disappointed" },
            },
          ],
        },
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "What is your role?" },
          subheader: { en: "Please select one of the following options:" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "Founder" },
            },
            {
              id: createId(),
              label: { en: "Executive" },
            },
            {
              id: createId(),
              label: { en: "Product Manager" },
            },
            {
              id: createId(),
              label: { en: "Product Owner" },
            },
            {
              id: createId(),
              label: { en: "Software Engineer" },
            },
          ],
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: { en: "What type of people do you think would most benefit from {{productName}}?" },
          required: true,
          inputType: "text",
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: { en: "What is the main benefit you receive from {{productName}}?" },
          required: true,
          inputType: "text",
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: { en: "How can we improve {{productName}} for you?" },
          subheader: { en: "Please be as specific as possible." },
          required: true,
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Onboarding Segmentation",
    category: "Product Experience",
    objectives: ["increase_user_adoption", "improve_user_retention"],
    description: "Learn more about who signed up to your product and why.",
    preset: {
      name: "Onboarding Segmentation",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "What is your role?" },
          subheader: { en: "Please select one of the following options:" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "Founder" },
            },
            {
              id: createId(),
              label: { en: "Executive" },
            },
            {
              id: createId(),
              label: { en: "Product Manager" },
            },
            {
              id: createId(),
              label: { en: "Product Owner" },
            },
            {
              id: createId(),
              label: { en: "Software Engineer" },
            },
          ],
        },
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "What's your company size?" },
          subheader: { en: "Please select one of the following options:" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "only me" },
            },
            {
              id: createId(),
              label: { en: "1-5 employees" },
            },
            {
              id: createId(),
              label: { en: "6-10 employees" },
            },
            {
              id: createId(),
              label: { en: "11-100 employees" },
            },
            {
              id: createId(),
              label: { en: "over 100 employees" },
            },
          ],
        },
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "How did you hear about us first?" },
          subheader: { en: "Please select one of the following options:" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "Recommendation" },
            },
            {
              id: createId(),
              label: { en: "Social Media" },
            },
            {
              id: createId(),
              label: { en: "Ads" },
            },
            {
              id: createId(),
              label: { en: "Google Search" },
            },
            {
              id: createId(),
              label: { en: "In a Podcast" },
            },
          ],
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Churn Survey",

    category: "Increase Revenue",
    objectives: ["sharpen_marketing_messaging", "improve_user_retention"],
    description: "Find out why people cancel their subscriptions. These insights are pure gold!",
    preset: {
      name: "Churn Survey",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          shuffleOption: "none",
          logic: [
            { value: "Difficult to use", condition: "equals", destination: "sxwpskjgzzpmkgfxzi15inif" },
            { value: "It's too expensive", condition: "equals", destination: "mao94214zoo6c1at5rpuz7io" },
            { value: "I am missing features", condition: "equals", destination: "l054desub14syoie7n202vq4" },
            { value: "Poor customer service", condition: "equals", destination: "hdftsos1odzjllr7flj4m3j9" },
            { value: "I just didn't need it anymore", condition: "equals", destination: "end" },
          ],
          choices: [
            { id: createId(), label: { en: "Difficult to use" } },
            { id: createId(), label: { en: "It's too expensive" } },
            { id: createId(), label: { en: "I am missing features" } },
            { id: createId(), label: { en: "Poor customer service" } },
            { id: createId(), label: { en: "I just didn't need it anymore" } },
          ],
          headline: { en: "Why did you cancel your subscription?" },
          required: true,
          subheader: { en: "We're sorry to see you leave. Help us do better:" },
        },
        {
          id: "sxwpskjgzzpmkgfxzi15inif",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "What would have made {{productName}} easier to use?" },
          required: true,
          subheader: { en: "" },
          buttonLabel: { en: "Send" },
          inputType: "text",
        },
        {
          id: "mao94214zoo6c1at5rpuz7io",
          html: {
            en: '<p class="fb-editor-paragraph" dir="ltr"><span>We\'d love to keep you as a customer. Happy to offer a 30% discount for the next year.</span></p>',
          },
          type: TSurveyQuestionType.CTA,
          logic: [{ condition: "clicked", destination: "end" }],
          headline: { en: "Get 30% off for the next year!" },
          required: true,
          buttonUrl: "https://formbricks.com",
          buttonLabel: { en: "Get 30% off" },
          buttonExternal: true,
          dismissButtonLabel: { en: "Skip" },
        },
        {
          id: "l054desub14syoie7n202vq4",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "What features are you missing?" },
          required: true,
          subheader: { en: "" },
          inputType: "text",
        },
        {
          id: "hdftsos1odzjllr7flj4m3j9",
          html: {
            en: '<p class="fb-editor-paragraph" dir="ltr"><span>We aim to provide the best possible customer service. Please email our CEO and she will personally handle your issue.</span></p>',
          },
          type: TSurveyQuestionType.CTA,
          logic: [{ condition: "clicked", destination: "end" }],
          headline: { en: "So sorry to hear 😔 Talk to our CEO directly!" },
          required: true,
          buttonUrl: "mailto:ceo@company.com",
          buttonLabel: { en: "Send email to CEO" },
          buttonExternal: true,
          dismissButtonLabel: { en: "Skip" },
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Earned Advocacy Score (EAS)",
    category: "Growth",
    objectives: ["support_sales", "sharpen_marketing_messaging"],
    description:
      "The EAS is a riff off the NPS but asking for actual past behaviour instead of lofty intentions.",
    preset: {
      name: "Earned Advocacy Score (EAS)",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          logic: [{ value: "No", condition: "equals", destination: "duz2qp8eftix9wty1l221x1h" }],
          shuffleOption: "none",
          choices: [
            { id: createId(), label: { en: "Yes" } },
            { id: createId(), label: { en: "No" } },
          ],
          headline: { en: "Have you actively recommended {{productName}} to others?" },
          required: true,
          subheader: { en: "" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "yhfew1j3ng6luy7t7qynwj79" }],
          headline: { en: "Great to hear! Why did you recommend us?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "duz2qp8eftix9wty1l221x1h",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "So sad. Why not?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "yhfew1j3ng6luy7t7qynwj79",
          type: TSurveyQuestionType.MultipleChoiceSingle,
          logic: [{ value: "No", condition: "equals", destination: "end" }],
          shuffleOption: "none",
          choices: [
            { id: createId(), label: { en: "Yes" } },
            { id: createId(), label: { en: "No" } },
          ],
          headline: { en: "Have you actively discouraged others from choosing {{productName}}?" },
          required: true,
          subheader: { en: "" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: { en: "What made you discourage them?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Improve Trial Conversion",
    category: "Increase Revenue",
    objectives: ["increase_user_adoption", "increase_conversion", "improve_user_retention"],
    description: "Find out why people stopped their trial. These insights help you improve your funnel.",
    preset: {
      name: "Improve Trial Conversion",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          shuffleOption: "none",
          logic: [
            {
              value: "I didn't get much value out of it",
              condition: "equals",
              destination: "aew2ymg51mffnt9db7duz9t3",
            },
            {
              value: "I expected something else",
              condition: "equals",
              destination: "rnrfydttavtsf2t2nfx1df7m",
            },
            {
              value: "It's too expensive for what it does",
              condition: "equals",
              destination: "x760wga1fhtr1i80cpssr7af",
            },
            {
              value: "I am missing a feature",
              condition: "equals",
              destination: "rbhww1pix03r6sl4xc511wqg",
            },
            { value: "I was just looking around", condition: "equals", destination: "end" },
          ],
          choices: [
            { id: createId(), label: { en: "I didn't get much value out of it" } },
            { id: createId(), label: { en: "I expected something else" } },
            { id: createId(), label: { en: "It's too expensive for what it does" } },
            { id: createId(), label: { en: "I am missing a feature" } },
            { id: createId(), label: { en: "I was just looking around" } },
          ],
          headline: { en: "Why did you stop your trial?" },
          required: true,
          subheader: { en: "Help us understand you better:" },
        },
        {
          id: "aew2ymg51mffnt9db7duz9t3",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "bqiyml1ym74ggx6htwdo7rlu" }],
          headline: { en: "Sorry to hear. What was the biggest problem using {{productName}}?" },
          required: true,
          buttonLabel: { en: "Next" },
          inputType: "text",
        },
        {
          id: "rnrfydttavtsf2t2nfx1df7m",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "bqiyml1ym74ggx6htwdo7rlu" }],
          headline: { en: "What did you expect {{productName}} would do for you?" },
          required: true,
          buttonLabel: { en: "Next" },
          inputType: "text",
        },
        {
          id: "x760wga1fhtr1i80cpssr7af",
          html: {
            en: '<p class="fb-editor-paragraph" dir="ltr"><span>We\'re happy to offer you a 20% discount on a yearly plan.</span></p>',
          },
          type: TSurveyQuestionType.CTA,
          logic: [{ condition: "clicked", destination: "end" }],
          headline: { en: "Sorry to hear! Get 20% off the first year." },
          required: true,
          buttonUrl: "https://formbricks.com/github",
          buttonLabel: { en: "Get 20% off" },
          buttonExternal: true,
          dismissButtonLabel: { en: "Skip" },
        },
        {
          id: "rbhww1pix03r6sl4xc511wqg",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "bqiyml1ym74ggx6htwdo7rlu" }],
          headline: { en: "Which features are you missing?" },
          required: true,
          subheader: { en: "What would you like to achieve?" },
          buttonLabel: { en: "Next" },
          inputType: "text",
        },
        {
          id: "bqiyml1ym74ggx6htwdo7rlu",
          type: TSurveyQuestionType.OpenText,
          logic: [
            { condition: "submitted", destination: "end" },
            { condition: "skipped", destination: "end" },
          ],
          headline: { en: "How are you solving your problem now?" },
          required: false,
          subheader: { en: "Please name alternative solutions:" },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Review Prompt",

    category: "Growth",
    objectives: ["support_sales"],
    description: "Invite users who love your product to review it publicly.",
    preset: {
      name: "Review Prompt",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          logic: [{ value: 3, condition: "lessEqual", destination: "tk9wpw2gxgb8fa6pbpp3qq5l" }],
          range: 5,
          scale: "star",
          headline: { en: "How do you like {{productName}}?" },
          required: true,
          subheader: { en: "" },
          lowerLabel: { en: "Not good" },
          upperLabel: { en: "Very satisfied" },
        },
        {
          id: createId(),
          html: { en: '<p class="fb-editor-paragraph" dir="ltr"><span>This helps us a lot.</span></p>' },
          type: TSurveyQuestionType.CTA,
          logic: [{ condition: "clicked", destination: "end" }],
          headline: { en: "Happy to hear 🙏 Please write a review for us!" },
          required: true,
          buttonUrl: "https://formbricks.com/github",
          buttonLabel: { en: "Write review" },
          buttonExternal: true,
        },
        {
          id: "tk9wpw2gxgb8fa6pbpp3qq5l",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Sorry to hear! What is ONE thing we can do better?" },
          required: true,
          subheader: { en: "Help us improve your experience." },
          buttonLabel: { en: "Send" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Interview Prompt",

    category: "Exploration",
    objectives: ["improve_user_retention"],
    description: "Invite a specific subset of your users to schedule an interview with your product team.",
    preset: {
      name: "Interview Prompt",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.CTA,
          headline: { en: "Do you have 15 min to talk to us? 🙏" },
          html: { en: "You're one of our power users. We would love to interview you briefly!" },
          buttonLabel: { en: "Book slot" },
          buttonUrl: "https://cal.com/johannes",
          buttonExternal: true,
          required: false,
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Reduce Onboarding Drop-Off",
    category: "Product Experience",
    objectives: ["increase_user_adoption", "increase_conversion"],
    description: "Identify weaknesses in your onboarding flow to increase user activation.",
    preset: {
      name: "Onboarding Drop-Off Reasons",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          shuffleOption: "none",
          logic: [
            {
              value: "Difficult to set up or use",
              condition: "equals",
              destination: "r0zvi3vburf4hm7qewimzjux",
            },
            {
              value: "Lacked features/functionality",
              condition: "equals",
              destination: "rbwz3y6y9avzqcfj30nu0qj4",
            },
            {
              value: "Just haven't had the time",
              condition: "equals",
              destination: "gn6298zogd2ipdz7js17qy5i",
            },
            {
              value: "Something else",
              condition: "equals",
              destination: "c0exdyri3erugrv0ezkyseh6",
            },
          ],
          choices: [
            { id: createId(), label: { en: "Didn't seem useful to me" } },
            { id: createId(), label: { en: "Difficult to set up or use" } },
            { id: createId(), label: { en: "Lacked features/functionality" } },
            { id: createId(), label: { en: "Just haven't had the time" } },
            { id: createId(), label: { en: "Something else" } },
          ],
          headline: { en: "What's the main reason why you haven't finished setting up {{productName}}?" },
          required: true,
          subheader: { en: "" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "What made you think {{productName}} wouldn't be useful?" },
          required: true,
          subheader: { en: "" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "r0zvi3vburf4hm7qewimzjux",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "What was difficult about setting up or using {{productName}}?" },
          required: true,
          subheader: { en: "" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "rbwz3y6y9avzqcfj30nu0qj4",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "What features or functionality were missing?" },
          required: true,
          subheader: { en: "" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "gn6298zogd2ipdz7js17qy5i",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "How could we make it easier for you to get started?" },
          required: true,
          subheader: { en: "" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "c0exdyri3erugrv0ezkyseh6",
          type: TSurveyQuestionType.OpenText,
          logic: [],
          headline: { en: "What was it? Please explain:" },
          required: false,
          subheader: { en: "We're eager to fix it asap." },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Uncover Strengths & Weaknesses",
    category: "Growth",
    objectives: ["sharpen_marketing_messaging", "improve_user_retention"],
    description: "Find out what users like and don't like about your product or offering.",
    preset: {
      name: "Uncover Strengths & Weaknesses",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          shuffleOption: "none",
          choices: [
            { id: createId(), label: { en: "Ease of use" } },
            { id: createId(), label: { en: "Good value for money" } },
            { id: createId(), label: { en: "It's open-source" } },
            { id: createId(), label: { en: "The founders are cute" } },
            { id: "other", label: { en: "Other" } },
          ],
          headline: { en: "What do you value most about {{productName}}?" },
          required: true,
          subheader: { en: "" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          shuffleOption: "none",
          choices: [
            { id: createId(), label: { en: "Documentation" } },
            { id: createId(), label: { en: "Customizability" } },
            { id: createId(), label: { en: "Pricing" } },
            { id: "other", label: { en: "Other" } },
          ],
          headline: { en: "What should we improve on?" },
          required: true,
          subheader: { en: "Please select one of the following options:" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Would you like to add something?" },
          required: false,
          subheader: { en: "Feel free to speak your mind, we do too." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Product Market Fit Survey (Short)",
    category: "Product Experience",
    description: "Measure PMF by assessing how disappointed users would be if your product disappeared.",
    preset: {
      name: "Product Market Fit Survey (Short)",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "How disappointed would you be if you could no longer use {{productName}}?" },
          subheader: { en: "Please select one of the following options:" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "Not at all disappointed" },
            },
            {
              id: createId(),
              label: { en: "Somewhat disappointed" },
            },
            {
              id: createId(),
              label: { en: "Very disappointed" },
            },
          ],
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: { en: "How can we improve {{productName}} for you?" },
          subheader: { en: "Please be as specific as possible." },
          required: true,
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Marketing Attribution",

    category: "Growth",
    objectives: ["increase_conversion", "sharpen_marketing_messaging"],
    description: "How did you first hear about us?",
    preset: {
      name: "Marketing Attribution",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "How did you hear about us first?" },
          subheader: { en: "Please select one of the following options:" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "Recommendation" },
            },
            {
              id: createId(),
              label: { en: "Social Media" },
            },
            {
              id: createId(),
              label: { en: "Ads" },
            },
            {
              id: createId(),
              label: { en: "Google Search" },
            },
            {
              id: createId(),
              label: { en: "In a Podcast" },
            },
          ],
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Changing subscription experience",

    category: "Increase Revenue",
    objectives: ["increase_conversion", "improve_user_retention"],
    description: "Find out what goes through peoples minds when changing their subscriptions.",
    preset: {
      name: "Changing subscription experience",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "How easy was it to change your plan?" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "Extremely difficult" },
            },
            {
              id: createId(),
              label: { en: "It took a while, but I got it" },
            },
            {
              id: createId(),
              label: { en: "It was alright" },
            },
            {
              id: createId(),
              label: { en: "Quite easy" },
            },
            {
              id: createId(),
              label: { en: "Very easy, love it!" },
            },
          ],
        },
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "Is the pricing information easy to understand?" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "Yes, very clear." },
            },
            {
              id: createId(),
              label: { en: "I was confused at first, but found what I needed." },
            },
            {
              id: createId(),
              label: { en: "Quite complicated." },
            },
          ],
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },

  {
    name: "Identify Customer Goals",

    category: "Product Experience",
    objectives: ["increase_user_adoption", "sharpen_marketing_messaging", "improve_user_retention"],
    description:
      "Better understand if your messaging creates the right expectations of the value your product provides.",
    preset: {
      name: "Identify Customer Goals",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "What's your primary goal for using {{productName}}?" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "Understand my user base deeply" },
            },
            {
              id: createId(),
              label: { en: "Identify upselling opportunities" },
            },
            {
              id: createId(),
              label: { en: "Build the best possible product" },
            },
            {
              id: createId(),
              label: { en: "Rule the world to make everyone breakfast brussels sprouts." },
            },
          ],
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Feature Chaser",

    category: "Product Experience",
    objectives: ["improve_user_retention"],
    description: "Follow up with users who just used a specific feature.",
    preset: {
      name: "Feature Chaser",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          range: 5,
          scale: "number",
          headline: { en: "How important is [ADD FEATURE] for you?" },
          required: true,
          lowerLabel: { en: "Not important" },
          upperLabel: { en: "Very important" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          shuffleOption: "none",
          choices: [
            { id: createId(), label: { en: "Aspect 1" } },
            { id: createId(), label: { en: "Aspect 2" } },
            { id: createId(), label: { en: "Aspect 3" } },
            { id: createId(), label: { en: "Aspect 4" } },
          ],
          headline: { en: "Which aspect is most important?" },
          required: true,
          subheader: { en: "" },
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Fake Door Follow-Up",

    category: "Exploration",
    objectives: ["increase_user_adoption"],
    description: "Follow up with users who ran into one of your Fake Door experiments.",
    preset: {
      name: "Fake Door Follow-Up",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          headline: { en: "How important is this feature for you?" },
          required: true,
          lowerLabel: { en: "Not important" },
          upperLabel: { en: "Very important" },
          range: 5,
          scale: "number",
        },
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceMulti,
          headline: { en: "What should be definitely include building this?" },
          required: false,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "Aspect 1" },
            },
            {
              id: createId(),
              label: { en: "Aspect 2" },
            },
            {
              id: createId(),
              label: { en: "Aspect 3" },
            },
            {
              id: createId(),
              label: { en: "Aspect 4" },
            },
          ],
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Feedback Box",

    category: "Product Experience",
    objectives: ["improve_user_retention"],
    description: "Give your users the chance to seamlessly share what's on their minds.",
    preset: {
      name: "Feedback Box",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          shuffleOption: "none",
          logic: [
            { value: "Bug report 🐞", condition: "equals", destination: "dnbiuq4l33l7jypcf2cg6vhh" },
            { value: "Feature Request 💡", condition: "equals", destination: "en9nuuevbf7g9oa9rzcs1l50" },
          ],
          choices: [
            { id: createId(), label: { en: "Bug report 🐞" } },
            { id: createId(), label: { en: "Feature Request 💡" } },
          ],
          headline: { en: "What's on your mind, boss?" },
          required: true,
          subheader: { en: "Thanks for sharing. We'll get back to you asap." },
        },
        {
          id: "dnbiuq4l33l7jypcf2cg6vhh",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "a6c76m5oocw6xp9agf3d2tam" }],
          headline: { en: "What's broken?" },
          required: true,
          subheader: { en: "The more detail, the better :)" },
          inputType: "text",
        },
        {
          id: "a6c76m5oocw6xp9agf3d2tam",
          html: {
            en: '<p class="fb-editor-paragraph" dir="ltr"><span>We will fix this as soon as possible. Do you want to be notified when we did?</span></p>',
          },
          type: TSurveyQuestionType.CTA,
          logic: [
            { condition: "clicked", destination: "end" },
            { condition: "skipped", destination: "end" },
          ],
          headline: { en: "Want to stay in the loop?" },
          required: false,
          buttonLabel: { en: "Yes, notify me" },
          buttonExternal: false,
          dismissButtonLabel: { en: "No, thanks" },
        },
        {
          id: "en9nuuevbf7g9oa9rzcs1l50",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Lovely, tell us more!" },
          required: true,
          subheader: { en: "What problem do you want us to solve?" },
          buttonLabel: { en: "Request feature" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Integration Setup Survey",

    category: "Product Experience",
    objectives: ["increase_user_adoption"],
    description: "Evaluate how easily users can add integrations to your product. Find blind spots.",
    preset: {
      name: "Integration Usage Survey",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: "s6ss6znzxdwjod1hv16fow4w",
          type: TSurveyQuestionType.Rating,
          logic: [{ value: 4, condition: "greaterEqual", destination: "ef0qo3l8iisd517ikp078u1p" }],
          range: 5,
          scale: "number",
          headline: { en: "How easy was it to set this integration up?" },
          required: true,
          subheader: { en: "" },
          lowerLabel: { en: "Not easy" },
          upperLabel: { en: "Very easy" },
        },
        {
          id: "mko13ptjj6tpi5u2pl7a5drz",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Why was it hard?" },
          required: false,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "ef0qo3l8iisd517ikp078u1p",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "What other tools would you like to use with {{productName}}?" },
          required: false,
          subheader: { en: "We keep building integrations, yours can be next:" },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "New Integration Survey",

    category: "Exploration",
    objectives: ["increase_user_adoption", "increase_conversion"],
    description: "Find out which integrations your users would like to see next.",
    preset: {
      name: "New Integration Survey",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "Which other tools are you using?" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "PostHog" },
            },
            {
              id: createId(),
              label: { en: "Segment" },
            },
            {
              id: createId(),
              label: { en: "Hubspot" },
            },
            {
              id: createId(),
              label: { en: "Twilio" },
            },
            {
              id: "other",
              label: { en: "Other" },
            },
          ],
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Docs Feedback",

    category: "Product Experience",
    objectives: ["increase_user_adoption", "improve_user_retention"],
    description: "Measure how clear each page of your developer documentation is.",
    preset: {
      name: "{{productName}} Docs Feedback",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "Was this page helpful?" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "Yes 👍" },
            },
            {
              id: createId(),
              label: { en: "No 👎" },
            },
          ],
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Please elaborate:" },
          required: false,
          inputType: "text",
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Page URL" },
          required: false,
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Net Promoter Score (NPS)",

    category: "Customer Success",
    objectives: ["support_sales"],
    description: "Measure the Net Promoter Score of your product.",
    preset: {
      name: "{{productName}} NPS",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.NPS,
          headline: { en: "How likely are you to recommend {{productName}} to a friend or colleague?" },
          required: false,
          lowerLabel: { en: "Not likely" },
          upperLabel: { en: "Very likely" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: { en: "What made you give that rating?" },
          required: false,
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Customer Satisfaction Score (CSAT)",

    category: "Customer Success",
    objectives: ["support_sales"],
    description: "Measure the Customer Satisfaction Score of your product.",
    preset: {
      name: "{{productName}} CSAT",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          logic: [{ value: 3, condition: "lessEqual", destination: "vyo4mkw4ln95ts4ya7qp2tth" }],
          range: 5,
          scale: "smiley",
          headline: { en: "How satisfied are you with your {{productName}} experience?" },
          required: true,
          subheader: { en: "" },
          lowerLabel: { en: "Not satisfied" },
          upperLabel: { en: "Very satisfied" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "Lovely! Is there anything we can do to improve your experience?" },
          required: false,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "vyo4mkw4ln95ts4ya7qp2tth",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Ugh, sorry! Is there anything we can do to improve your experience?" },
          required: false,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Identify upsell opportunities",

    category: "Increase Revenue",
    objectives: ["support_sales", "sharpen_marketing_messaging"],
    description: "Find out how much time your product saves your user. Use it to upsell.",
    preset: {
      name: "Identify upsell opportunities",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "How many hours does your team save per week by using {{productName}}?" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "Less than 1 hour" },
            },
            {
              id: createId(),
              label: { en: "1 to 2 hours" },
            },
            {
              id: createId(),
              label: { en: "3 to 5 hours" },
            },
            {
              id: createId(),
              label: { en: "5+ hours" },
            },
          ],
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },

  {
    name: "Prioritize Features",

    category: "Exploration",
    objectives: ["increase_user_adoption"],
    description: "Identify features your users need most and least.",
    preset: {
      name: "Feature Prioritization",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          logic: [],
          shuffleOption: "none",
          choices: [
            { id: createId(), label: { en: "Feature 1" } },
            { id: createId(), label: { en: "Feature 2" } },
            { id: createId(), label: { en: "Feature 3" } },
            { id: "other", label: { en: "Other" } },
          ],
          headline: { en: "Which of these features would be MOST valuable to you?" },
          required: true,
          subheader: { en: "" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          logic: [],
          shuffleOption: "none",
          choices: [
            { id: createId(), label: { en: "Feature 1" } },
            { id: createId(), label: { en: "Feature 2" } },
            { id: createId(), label: { en: "Feature 3" } },
          ],
          headline: { en: "Which of these features would be LEAST valuable to you?" },
          required: true,
          subheader: { en: "" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: { en: "How else could we improve you experience with {{productName}}?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Gauge Feature Satisfaction",

    category: "Product Experience",
    objectives: ["increase_user_adoption", "improve_user_retention"],
    description: "Evaluate the satisfaction of specific features of your product.",
    preset: {
      name: "Gauge Feature Satisfaction",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          headline: { en: "How easy was it to achieve ... ?" },
          required: true,
          lowerLabel: { en: "Not easy" },
          upperLabel: { en: "Very easy" },
          scale: "number",
          range: 5,
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: { en: "What is one thing we could do better?" },
          required: false,
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Marketing Site Clarity",

    category: "Growth",
    objectives: ["increase_conversion", "sharpen_marketing_messaging"],
    description: "Identify users dropping off your marketing site. Improve your messaging.",
    preset: {
      name: "Marketing Site Clarity",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          headline: { en: "Do you have all the info you need to give {{productName}} a try?" },
          required: true,
          shuffleOption: "none",
          choices: [
            {
              id: createId(),
              label: { en: "Yes, totally" },
            },
            {
              id: createId(),
              label: { en: "Kind of..." },
            },
            {
              id: createId(),
              label: { en: "No, not at all" },
            },
          ],
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: { en: "What’s missing or unclear to you about {{productName}}?" },
          required: false,
          inputType: "text",
        },
        {
          id: createId(),
          type: TSurveyQuestionType.CTA,
          headline: { en: "Thanks for your answer! Get 25% off your first 6 months:" },
          required: false,
          buttonLabel: { en: "Get discount" },
          buttonUrl: "https://app.formbricks.com/auth/signup",
          buttonExternal: true,
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Customer Effort Score (CES)",

    category: "Product Experience",
    objectives: ["increase_user_adoption", "improve_user_retention"],
    description: "Determine how easy it is to use a feature.",
    preset: {
      name: "Customer Effort Score (CES)",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          range: 5,
          scale: "number",
          headline: { en: "{{productName}} makes it easy for me to [ADD GOAL]" },
          required: true,
          subheader: { en: "" },
          lowerLabel: { en: "Disagree strongly" },
          upperLabel: { en: "Agree strongly" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Thanks! How could we make it easier for you to [ADD GOAL]?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },

  {
    name: "Rate Checkout Experience",

    category: "Increase Revenue",
    objectives: ["increase_conversion"],
    description: "Let customers rate the checkout experience to tweak conversion.",
    preset: {
      name: "Rate Checkout Experience",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          logic: [{ value: 4, condition: "greaterEqual", destination: "lpof3d9t9hmnqvyjlpksmxd7" }],
          range: 5,
          scale: "number",
          headline: { en: "How easy or difficult was it to complete the checkout?" },
          required: true,
          subheader: { en: "" },
          lowerLabel: { en: "Very difficult" },
          upperLabel: { en: "Very easy" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "Sorry about that! What would have made it easier for you?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "lpof3d9t9hmnqvyjlpksmxd7",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Lovely! Is there anything we can do to improve your experience?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Measure Search Experience",

    category: "Product Experience",
    objectives: ["improve_user_retention"],
    description: "Measure how relevant your search results are.",
    preset: {
      name: "Measure Search Experience",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          logic: [{ value: 4, condition: "greaterEqual", destination: "adcs3d9t9hmnqvyjlpksmxd7" }],
          range: 5,
          scale: "number",
          headline: { en: "How relevant are these search results?" },
          required: true,
          subheader: { en: "" },
          lowerLabel: { en: "Not at all relevant" },
          upperLabel: { en: "Very relevant" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "Ugh! What makes the results irrelevant for you?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "adcs3d9t9hmnqvyjlpksmxd7",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Lovely! Is there anything we can do to improve your experience?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Evaluate Content Quality",

    category: "Growth",
    objectives: ["increase_conversion"],
    description: "Measure if your content marketing pieces hit right.",
    preset: {
      name: "Evaluate Content Quality",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          logic: [{ value: 4, condition: "greaterEqual", destination: "adcs3d9t9hmnqvyjlpkswi38" }],
          range: 5,
          scale: "number",
          headline: { en: "How well did this article address what you were hoping to learn?" },
          required: true,
          subheader: { en: "" },
          lowerLabel: { en: "Not at all well" },
          upperLabel: { en: "Extremely well" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "Hmpft! What were you hoping for?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "adcs3d9t9hmnqvyjlpkswi38",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Lovely! Is there anything else you would like us to cover?" },
          required: true,
          placeholder: { en: "Topics, trends, tutorials..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Measure Task Accomplishment",

    category: "Customer Success",
    objectives: ["increase_user_adoption", "improve_user_retention"],
    description: "See if people get their 'Job To Be Done' done. Successful people are better customers.",
    preset: {
      name: "Measure Task Accomplishment",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          shuffleOption: "none",
          logic: [
            { value: "Working on it, boss", condition: "equals", destination: "nq88udm0jjtylr16ax87xlyc" },
            { value: "Yes", condition: "equals", destination: "rjeac33gd13h3nnbrbid1fb2" },
            { value: "No", condition: "equals", destination: "u83zhr66knyfozccoqojx7bc" },
          ],
          choices: [
            { id: createId(), label: { en: "Yes" } },
            { id: createId(), label: { en: "Working on it, boss" } },
            { id: createId(), label: { en: "No" } },
          ],
          headline: { en: "Were you able to accomplish what you came here to do today?" },
          required: true,
        },
        {
          id: "rjeac33gd13h3nnbrbid1fb2",
          type: TSurveyQuestionType.Rating,
          logic: [{ value: 4, condition: "greaterEqual", destination: "nq88udm0jjtylr16ax87xlyc" }],
          range: 5,
          scale: "number",
          headline: { en: "How easy was it to achieve your goal?" },
          required: true,
          lowerLabel: { en: "Very difficult" },
          upperLabel: { en: "Very easy" },
        },
        {
          id: "s0999bhpaz8vgf7ps264piek",
          type: TSurveyQuestionType.OpenText,
          logic: [
            { condition: "submitted", destination: "end" },
            { condition: "skipped", destination: "end" },
          ],
          headline: { en: "What made it hard?" },
          required: false,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "nq88udm0jjtylr16ax87xlyc",
          type: TSurveyQuestionType.OpenText,
          logic: [
            { condition: "skipped", destination: "end" },
            { condition: "submitted", destination: "end" },
          ],
          headline: { en: "Great! What did you come here to do today?" },
          required: false,
          buttonLabel: { en: "Send" },
          inputType: "text",
        },
        {
          id: "u83zhr66knyfozccoqojx7bc",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "What stopped you?" },
          required: true,
          buttonLabel: { en: "Send" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Identify Sign Up Barriers",

    category: "Growth",
    objectives: ["increase_conversion"],
    description: "Offer a discount to gather insights about sign up barriers.",
    preset: {
      name: "{{productName}} Sign Up Barriers",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          html: {
            en: '<p class="fb-editor-paragraph" dir="ltr"><span>You seem to be considering signing up. Answer four questions and get 10% on any plan.</span></p>',
          },
          type: TSurveyQuestionType.CTA,
          logic: [{ condition: "skipped", destination: "end" }],
          headline: { en: "Answer this short survey, get 10% off!" },
          required: false,
          buttonLabel: { en: "Get 10% discount" },
          buttonExternal: false,
          dismissButtonLabel: { en: "No, thanks" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          logic: [{ value: "5", condition: "equals", destination: "end" }],
          range: 5,
          scale: "number",
          headline: { en: "How likely are you to sign up for {{productName}}?" },
          required: true,
          subheader: { en: "" },
          lowerLabel: { en: "Not at all likely" },
          upperLabel: { en: "Very likely" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.MultipleChoiceSingle,
          shuffleOption: "none",
          logic: [
            {
              value: "May not have what I'm looking for",
              condition: "equals",
              destination: "atiw0j1oykb77zr0b7q4tixu",
            },
            {
              value: "Still comparing options",
              condition: "equals",
              destination: "j7jkpolm5xl7u0zt3g0e4z7d",
            },
            { value: "Seems complicated", condition: "equals", destination: "t5gvag2d7kq311szz5iyiy79" },
            { value: "Pricing is a concern", condition: "equals", destination: "or0yhhrof753sq9ug4mdavgz" },
            { value: "Something else", condition: "equals", destination: "v0pq1qcnm6ohiry5ywcd91qq" },
          ],
          choices: [
            { id: createId(), label: { en: "May not have what I'm looking for" } },
            { id: createId(), label: { en: "Still comparing options" } },
            { id: createId(), label: { en: "Seems complicated" } },
            { id: createId(), label: { en: "Pricing is a concern" } },
            { id: createId(), label: { en: "Something else" } },
          ],
          headline: { en: "What is holding you back from trying {{productName}}?" },
          required: true,
          subheader: { en: "" },
        },
        {
          id: "atiw0j1oykb77zr0b7q4tixu",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "k3q0vt1ko0bzbsq076p7lnys" }],
          headline: { en: "What do you need but {{productName}} does not offer?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },

        {
          id: "j7jkpolm5xl7u0zt3g0e4z7d",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "k3q0vt1ko0bzbsq076p7lnys" }],
          headline: { en: "What options are you looking at?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "t5gvag2d7kq311szz5iyiy79",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "k3q0vt1ko0bzbsq076p7lnys" }],
          headline: { en: "What seems complicated to you?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "or0yhhrof753sq9ug4mdavgz",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "k3q0vt1ko0bzbsq076p7lnys" }],
          headline: { en: "What are you concerned about regarding pricing?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "v0pq1qcnm6ohiry5ywcd91qq",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Please explain:" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "k3q0vt1ko0bzbsq076p7lnys",
          html: {
            en: '<p class="fb-editor-paragraph" dir="ltr"><span>Thanks a lot for taking the time to share feedback 🙏</span></p>',
          },
          type: TSurveyQuestionType.CTA,
          headline: { en: "Thanks! Here is your code: SIGNUPNOW10" },
          required: false,
          buttonUrl: "https://app.formbricks.com/auth/signup",
          buttonLabel: { en: "Sign Up" },
          buttonExternal: true,
          dismissButtonLabel: { en: "Skip for now" },
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Build Product Roadmap",

    category: "Exploration",
    objectives: ["increase_user_adoption"],
    description: "Identify the ONE thing your users want the most and build it.",
    preset: {
      name: "{{productName}} Roadmap Input",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          range: 5,
          scale: "number",
          headline: { en: "How satisfied are you with the features and functionality of {{productName}}?" },
          required: true,
          subheader: { en: "" },
          lowerLabel: { en: "Not at all satisfied" },
          upperLabel: { en: "Extremely satisfied" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.OpenText,
          headline: {
            en: "What's ONE change we could make to improve your {{productName}} experience most?",
          },
          required: true,
          subheader: { en: "" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Understand Purchase Intention",

    category: "Increase Revenue",
    objectives: ["increase_conversion", "increase_user_adoption"],
    description: "Find out how close your visitors are to buy or subscribe.",
    preset: {
      name: "Purchase Intention Survey",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          logic: [
            { value: "2", condition: "lessEqual", destination: "y19mwcmstlc7pi7s4izxk1ll" },
            { value: "3", condition: "equals", destination: "zm1hs8qkeuidh3qm0hx8pnw7" },
            { value: "4", condition: "equals", destination: "zm1hs8qkeuidh3qm0hx8pnw7" },
            { value: "5", condition: "equals", destination: "end" },
          ],
          range: 5,
          scale: "number",
          headline: { en: "How likely are you to subscribe to {{productName}} today?" },
          required: true,
          subheader: { en: "" },
          lowerLabel: { en: "Not at all likely" },
          upperLabel: { en: "Extremely likely" },
        },
        {
          id: "y19mwcmstlc7pi7s4izxk1ll",
          type: TSurveyQuestionType.OpenText,
          logic: [
            { condition: "submitted", destination: "end" },
            { condition: "skipped", destination: "end" },
          ],
          headline: { en: "Got it. What's your primary reason for visiting today?" },
          required: false,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "zm1hs8qkeuidh3qm0hx8pnw7",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "What, if anything, is holding you back from making a purchase today?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Improve Newsletter Content",
    category: "Growth",
    objectives: ["increase_conversion", "sharpen_marketing_messaging"],
    description: "Find out how your subscribers like your newsletter content.",
    preset: {
      name: "Improve Newsletter Content",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          logic: [
            { value: "5", condition: "equals", destination: "l2q1chqssong8n0xwaagyl8g" },
            { value: "5", condition: "lessThan", destination: "k3s6gm5ivkc5crpycdbpzkpa" },
          ],
          range: 5,
          scale: "smiley",
          headline: { en: "How would you rate this weeks newsletter?" },
          required: true,
          subheader: { en: "" },
          lowerLabel: { en: "Meh" },
          upperLabel: { en: "Great" },
        },
        {
          id: "k3s6gm5ivkc5crpycdbpzkpa",
          type: TSurveyQuestionType.OpenText,
          logic: [
            { condition: "submitted", destination: "end" },
            { condition: "skipped", destination: "end" },
          ],
          headline: { en: "What would have made this weeks newsletter more helpful?" },
          required: false,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "l2q1chqssong8n0xwaagyl8g",
          html: {
            en: '<p class="fb-editor-paragraph" dir="ltr"><span>Who thinks like you? You\'d do us a huge favor if you\'d share this weeks episode with your brain friend!</span></p>',
          },
          type: TSurveyQuestionType.CTA,
          headline: { en: "Thanks! ❤️ Spread the love with ONE friend." },
          required: false,
          buttonUrl: "https://formbricks.com",
          buttonLabel: { en: "Happy to help!" },
          buttonExternal: true,
          dismissButtonLabel: { en: "Find your own friends" },
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Evaluate a Product Idea",

    category: "Exploration",
    objectives: ["improve_user_retention", "increase_user_adoption"],
    description: "Survey users about product or feature ideas. Get feedback rapidly.",
    preset: {
      name: "Evaluate a Product Idea",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: createId(),
          html: {
            en: '<p class="fb-editor-paragraph" dir="ltr"><span>We respect your time and kept it short 🤸</span></p>',
          },
          type: TSurveyQuestionType.CTA,
          headline: {
            en: "We love how you use {{productName}}! We'd love to pick your brain on a feature idea. Got a minute?",
          },
          required: true,
          buttonLabel: { en: "Let's do it!" },
          buttonExternal: false,
          dismissButtonLabel: { en: "Skip" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          logic: [
            { value: "3", condition: "lessEqual", destination: "ndacjg9lqf5jcpq9w8ote666" },
            { value: "4", condition: "greaterEqual", destination: "jmzgbo73cfjswlvhoynn7o0q" },
          ],
          range: 5,
          scale: "number",
          headline: { en: "Thanks! How difficult or easy is it for you to [PROBLEM AREA] today?" },
          required: true,
          subheader: { en: "" },
          lowerLabel: { en: "Very difficult" },
          upperLabel: { en: "Very easy" },
        },
        {
          id: "ndacjg9lqf5jcpq9w8ote666",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "What's most difficult for you when it comes to [PROBLEM AREA]?" },
          required: true,
          subheader: { en: "" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "jmzgbo73cfjswlvhoynn7o0q",
          html: {
            en: '<p class="fb-editor-paragraph"><br></p><p class="fb-editor-paragraph" dir="ltr"><b><strong class="fb-editor-text-bold">Read the text below, then answer 2 questions:</strong></b></p><p class="fb-editor-paragraph"><br></p><p class="fb-editor-paragraph" dir="ltr"><span>Insert concept brief here. Add neccessary details but keep it concise and easy to understand.</span></p>',
          },
          type: TSurveyQuestionType.CTA,
          headline: { en: "We're working on an idea to help with [PROBLEM AREA]." },
          required: true,
          buttonLabel: { en: "Next" },
          buttonExternal: false,
          dismissButtonLabel: { en: "Skip" },
        },
        {
          id: createId(),
          type: TSurveyQuestionType.Rating,
          logic: [
            { value: "3", condition: "lessEqual", destination: "mmiuun3z4e7gk4ufuwh8lq8q" },
            { value: "4", condition: "greaterEqual", destination: "gvzevzw4hkqd6dmlkcly6kd1" },
          ],
          range: 5,
          scale: "number",
          headline: { en: "How valuable would this feature be to you?" },
          required: true,
          subheader: { en: "" },
          lowerLabel: { en: "Not valuable" },
          upperLabel: { en: "Very valuable" },
        },
        {
          id: "mmiuun3z4e7gk4ufuwh8lq8q",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "bqmnpyku9etsgbtb322luzb2" }],
          headline: { en: "Got it. Why wouldn't this feature be valuable to you?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "gvzevzw4hkqd6dmlkcly6kd1",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Got it. What would be most valuable to you in this feature?" },
          required: true,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "bqmnpyku9etsgbtb322luzb2",
          type: TSurveyQuestionType.OpenText,
          headline: { en: "Anything else we should keep in mind?" },
          required: false,
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },
  {
    name: "Understand Low Engagement",

    category: "Product Experience",
    objectives: ["improve_user_retention", "increase_user_adoption"],
    description: "Identify reasons for low engagement to improve user adoption.",
    preset: {
      name: "Reasons for Low Engagement",
      welcomeCard: welcomeCardDefault,
      questions: [
        {
          id: "aq9dafe9nxe0kpm67b1os2z9",
          type: TSurveyQuestionType.MultipleChoiceSingle,
          shuffleOption: "none",
          logic: [
            { value: "Difficult to use", condition: "equals", destination: "r0zvi3vburf4hm7qewimzjux" },
            {
              value: "Found a better alternative",
              condition: "equals",
              destination: "g92s5wetp51ps6afmc6y7609",
            },
            {
              value: "Just haven't had the time",
              condition: "equals",
              destination: "gn6298zogd2ipdz7js17qy5i",
            },
            {
              value: "Lacked features I need",
              condition: "equals",
              destination: "rbwz3y6y9avzqcfj30nu0qj4",
            },
            { value: "Other", condition: "equals", destination: "c0exdyri3erugrv0ezkyseh6" },
          ],
          choices: [
            { id: "xoqb0wjjsk4t0lx0i7jrhx26", label: { en: "Difficult to use" } },
            { id: "p768nlw47ndehtgzx6m82dr6", label: { en: "Found a better alternative" } },
            { id: "izt28ma5ep3s92531owxj1vg", label: { en: "Just haven't had the time" } },
            { id: "dhkp2wb9e1tv7kfu8csjhzbh", label: { en: "Lacked features I need" } },
            { id: "other", label: { en: "Other" } },
          ],
          headline: { en: "What's the main reason you haven't been back to {{productName}} recently?" },
          required: true,
          subheader: { en: "" },
        },
        {
          id: "r0zvi3vburf4hm7qewimzjux",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "What's difficult about using {{productName}}?" },
          required: true,
          subheader: { en: "" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "g92s5wetp51ps6afmc6y7609",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "Got it. Which alternative are you using instead?" },
          required: true,
          subheader: { en: "" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "gn6298zogd2ipdz7js17qy5i",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "Got it. How could we make it easier for you to get started?" },
          required: true,
          subheader: { en: "" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "rbwz3y6y9avzqcfj30nu0qj4",
          type: TSurveyQuestionType.OpenText,
          logic: [{ condition: "submitted", destination: "end" }],
          headline: { en: "Got it. What features or functionality were missing?" },
          required: true,
          subheader: { en: "" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
        {
          id: "c0exdyri3erugrv0ezkyseh6",
          type: TSurveyQuestionType.OpenText,
          logic: [],
          headline: { en: "Please add more details:" },
          required: false,
          subheader: { en: "" },
          placeholder: { en: "Type your answer here..." },
          inputType: "text",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },

  /* {
    name: "TEMPLATE MASTER",

    category: "X",
    objectives: ["X"],
    description: "X",
    preset: {
      name: "X",
      welcomeCard: welcomeCardDefault,
questions: [

        {
          id: createId(),
          type: "X",
          headline: "X",
          required: false,
          lowerLabel: "Not likely",
          upperLabel: "Very likely",
        },
      ],
      thankYouCard: thankYouCardDefault,
      hiddenFields: hiddenFieldsDefault,
    },
  },  */
];

export const customSurvey = {
  name: "Start from scratch",
  description: "Create a survey without template.",
  preset: {
    name: "New Survey",
    welcomeCard: welcomeCardDefault,
    questions: [
      {
        id: createId(),
        type: TSurveyQuestionType.OpenText,
        headline: { en: "What would you like to know?" },
        subheader: { en: "This is an example survey." },
        placeholder: { en: "Type your answer here..." },
        required: true,
        inputType: "text",
      } as TSurveyOpenTextQuestion,
    ],
    thankYouCard: thankYouCardDefault,
    hiddenFields: hiddenFieldsDefault,
  },
};

export const minimalSurvey: TSurvey = {
  id: "someUniqueId1",
  createdAt: new Date(),
  updatedAt: new Date(),
  name: "Minimal Survey",
  type: "web",
  environmentId: "someEnvId1",
  createdBy: null,
  status: "draft",
  attributeFilters: [],
  displayOption: "displayOnce",
  autoClose: null,
  triggers: [],
  redirectUrl: null,
  recontactDays: null,
  welcomeCard: welcomeCardDefault,
  questions: [],
  thankYouCard: {
    enabled: false,
  },
  hiddenFields: {
    enabled: false,
  },
  delay: 0, // No delay
  displayPercentage: null,
  autoComplete: null,
  closeOnDate: null,
  surveyClosedMessage: {
    enabled: false,
  },
  productOverwrites: null,
  singleUse: null,
  styling: null,
  resultShareKey: null,
};
