apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spicedb-operator.fullname" . }}-update-graph
  labels:
    {{- include "spicedb-operator.labels" . | nindent 4 }}
data:
  update-graph.yaml: |
{{ .Files.Get "files/update-graph.yaml" | indent 4 }}
