apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spicedb-operator.fullname" . }}
  labels:
    {{- include "spicedb-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "spicedb-operator.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/update-graph: {{ .Files.Get "files/update-graph.yaml" | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "spicedb-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "spicedb-operator.fullname" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: spicedb-operator
          image: {{ include "spicedb-operator.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - run
            - --crd=false
            - --config=/opt/operator/update-graph.yaml
            - --watch-namespaces={{ include "spicedb-operator.watchNamespaces" . }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 10
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            timeoutSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - name: update-graph
              mountPath: /opt/operator
              readOnly: true
      volumes:
        - name: update-graph
          configMap:
            name: {{ include "spicedb-operator.fullname" . }}-update-graph
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
