apiVersion: v1
kind: Service
metadata:
  name: {{ include "spicedb-operator.fullname" . }}
  labels:
    {{- include "spicedb-operator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "spicedb-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
