export const CLOUD_PRICING_DATA = {
  plans: [
    {
      name: "environments.settings.billing.free",
      id: "free",
      featured: false,
      description: "environments.settings.billing.free_description",
      price: { monthly: "$0", yearly: "$0" },
      mainFeatures: [
        "environments.settings.billing.unlimited_surveys",
        "environments.settings.billing.unlimited_team_members",
        "environments.settings.billing.3_projects",
        "environments.settings.billing.1500_monthly_responses",
        "environments.settings.billing.2000_monthly_identified_users",
        "environments.settings.billing.website_surveys",
        "environments.settings.billing.app_surveys",
        "environments.settings.billing.unlimited_apps_websites",
        "environments.settings.billing.link_surveys",
        "environments.settings.billing.email_embedded_surveys",
        "environments.settings.billing.logic_jumps_hidden_fields_recurring_surveys",
        "environments.settings.billing.api_webhooks",
        "environments.settings.billing.all_integrations",
        "environments.settings.billing.all_surveying_features",
      ],
      href: "https://app.formbricks.com/auth/signup?plan=free",
    },
    {
      name: "environments.settings.billing.startup",
      id: "startup",
      featured: false,
      description: "environments.settings.billing.startup_description",
      price: { monthly: "$39", yearly: "$390 " },
      mainFeatures: [
        "environments.settings.billing.everything_in_free",
        "environments.settings.billing.unlimited_surveys",
        "environments.settings.billing.remove_branding",
        "environments.settings.billing.email_support",
        "environments.settings.billing.3_projects",
        "environments.settings.billing.5000_monthly_responses",
        "environments.settings.billing.7500_monthly_identified_users",
      ],
      href: "https://app.formbricks.com/auth/signup?plan=startup",
    },
    {
      name: "environments.settings.billing.scale",
      id: "scale",
      featured: true,
      description: "environments.settings.billing.scale_description",
      price: { monthly: "$149", yearly: "$1,490" },
      mainFeatures: [
        "environments.settings.billing.everything_in_startup",
        "environments.settings.billing.team_access_roles",
        "environments.settings.billing.multi_language_surveys",
        "environments.settings.billing.advanced_targeting",
        "environments.settings.billing.priority_support",
        "environments.settings.billing.5_projects",
        "environments.settings.billing.10000_monthly_responses",
        "environments.settings.billing.30000_monthly_identified_users",
      ],
      href: "https://app.formbricks.com/auth/signup?plan=scale",
    },
    {
      name: "environments.settings.billing.enterprise",
      id: "enterprise",
      featured: false,
      description: "environments.settings.billing.enterprise_description",
      price: {
        monthly: "environments.settings.billing.say_hi",
        yearly: "environments.settings.billing.say_hi",
      },
      mainFeatures: [
        "environments.settings.billing.everything_in_scale",
        "environments.settings.billing.custom_project_limit",
        "environments.settings.billing.custom_miu_limit",
        "environments.settings.billing.premium_support_with_slas",
        "environments.settings.billing.uptime_sla_99",
        "environments.settings.billing.customer_success_manager",
        "environments.settings.billing.technical_onboarding",
      ],
      href: "https://cal.com/johannes/enterprise-cloud",
    },
  ],
};
