name: Build
on:
  workflow_call:
jobs:
  build:
    name: Build Formbricks-com
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install --config.platform=linux --config.architecture=x64

      - name: Build Formbricks-com
        run: pnpm build --filter=formbricks-com...
