name: Cron - Weekly summary

on:
  workflow_dispatch:
  # "Scheduled workflows run on the latest commit on the default or base branch."
  # — https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule
  schedule:
    # Runs “At 08:00 on Monday.” (see https://crontab.guru)
    - cron: "0 8 * * 1"
permissions:
  contents: read

jobs:
  cron-weeklySummary:
    permissions:
      contents: read    
    env:
      APP_URL: ${{ secrets.APP_URL }}
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481
        with:
          egress-policy: audit
      - name: cURL request
        if: ${{ env.APP_URL && env.CRON_SECRET }}
        run: |
          curl ${{ env.APP_URL }}/api/cron/weekly-summary \
            -X POST \
            -H 'content-type: application/json' \
            -H 'x-api-key: ${{ env.CRON_SECRET }}' \
            --fail
