name: Test Boolean Logic

on:
  workflow_dispatch:
    inputs:
      IS_PRERELEASE:
        description: "Whether this is a prerelease (affects latest tag)"
        required: false
        type: "boolean"
        default: "false"

jobs:
  test-logic:
    runs-on: ubuntu-latest
    steps:
      - name: Test Boolean Expressions
        run: |
          echo "=== Testing Boolean Logic ==="
          echo "Input IS_PRERELEASE: ${{ inputs.IS_PRERELEASE }}"
          echo "Input type: ${{ type(inputs.IS_PRERELEASE) }}"
          echo ""

          echo "=== Current Logic (string comparison) ==="
          echo "Expression: inputs.IS_PRERELEASE != 'true'"
          echo "Result: ${{ inputs.IS_PRERELEASE != 'true' }}"
          echo "Should tag as latest: ${{ inputs.IS_PRERELEASE != 'true' }}"
          echo ""

          echo "=== Alternative Logic (boolean negation) ==="
          echo "Expression: !inputs.IS_PRERELEASE"
          echo "Result: ${{ !inputs.IS_PRERELEASE }}"
          echo "Should tag as latest: ${{ !inputs.IS_PRERELEASE }}"
          echo ""

          echo "=== Test Cases ==="
          echo "When IS_PRERELEASE=true (pre-release):"
          echo "  String comparison result: ${{ true != 'true' }}"
          echo "  Boolean negation result: ${{ !true }}"
          echo ""
          echo "When IS_PRERELEASE=false (stable release):"
          echo "  String comparison result: ${{ false != 'true' }}"
          echo "  Boolean negation result: ${{ !false }}"

      - name: Simulate Docker Metadata Tags
        run: |
          echo "=== Simulated Docker Tags ==="
          echo "Version tags: v1.0.0, 1.0.0, 1.0, 1"
          echo "Latest tag enabled: ${{ inputs.IS_PRERELEASE != 'true' }}"
          if [[ "${{ inputs.IS_PRERELEASE != 'true' }}" == "true" ]]; then
            echo "✅ Would add 'latest' tag"
          else
            echo "❌ Would NOT add 'latest' tag"
          fi
