name: Upload Sentry Sourcemaps (Manual)

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: "Docker image to extract sourcemaps from"
        required: true
        type: string
      release_version:
        description: "Release version (e.g., v1.2.3)"
        required: true
        type: string
      tag_version:
        description: "Docker image tag (leave empty to use release_version)"
        required: false
        type: string

permissions:
  contents: read

jobs:
  upload-sourcemaps:
    name: Upload Sourcemaps to Sentry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set Docker Image
        run: echo "DOCKER_IMAGE=${DOCKER_IMAGE}" >> $GITHUB_ENV
        env:
          DOCKER_IMAGE: ${{ inputs.docker_image }}:${{ inputs.tag_version != '' && inputs.tag_version || inputs.release_version }}

      - name: Upload Sourcemaps to Sentry
        uses: ./.github/actions/upload-sentry-sourcemaps
        with:
          docker_image: ${{ env.DOCKER_IMAGE }}
          release_version: ${{ inputs.release_version }}
          sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
