import type { Template } from "@formbricks/types/templates";
import {
  AppPieChartIcon,
  ArrowRightCircleIcon,
  ArrowUpRightIcon,
  BaseballIcon,
  CancelSubscriptionIcon,
  CashCalculatorIcon,
  CheckMarkIcon,
  CodeBookIcon,
  DashboardIcon,
  DogChaserIcon,
  DoorIcon,
  FeedbackIcon,
  GaugeSpeedFastIcon,
  HeartCommentIcon,
  InterviewPromptIcon,
  LoadingBarIcon,
  OnboardingIcon,
  PMFIcon,
  TaskListSearchIcon,
  UserSearchGlasIcon,
  VideoTabletAdjustIcon,
} from "@formbricks/ui";
import { createId } from "@paralleldrive/cuid2";

const thankYouCardDefault = {
  enabled: true,
  headline: "Thank you!",
  subheader: "We appreciate your feedback.",
};

export const templates: Template[] = [
  {
    name: "Product Market Fit Survey (short)",
    icon: PMFIcon,
    category: "Product Experience",

    description: "Measure PMF by assessing how disappointed users would be if your product disappeared.",
    preset: {
      name: "Product Market Fit Survey (short)",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "How disappointed would you be if you could no longer use {{productName}}?",
          subheader: "Please select one of the following options:",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Not at all disappointed",
            },
            {
              id: createId(),
              label: "Somewhat disappointed",
            },
            {
              id: createId(),
              label: "Very disappointed",
            },
          ],
        },
        {
          id: createId(),
          type: "openText",
          headline: "How can we improve {{productName}} for you?",
          subheader: "Please be as specific as possible.",
          required: true,
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Product Market Fit (Superhuman)",
    icon: PMFIcon,
    category: "Product Experience",

    description: "Measure PMF by assessing how disappointed users would be if your product disappeared.",
    preset: {
      name: "Product Market Fit (Superhuman)",
      questions: [
        {
          id: createId(),
          html: '<p class="fb-editor-paragraph" dir="ltr"><span>We would love to understand your user experience better. Sharing your insight helps a lot!</span></p>',
          type: "cta",
          logic: [{ condition: "skipped", destination: "end" }],
          headline: "You are one of our power users! Do you have 5 minutes?",
          required: false,
          buttonLabel: "Happy to help!",
          buttonExternal: false,
          dismissButtonLabel: "No, thanks.",
        },
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "How disappointed would you be if you could no longer use {{productName}}?",
          subheader: "Please select one of the following options:",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Not at all disappointed",
            },
            {
              id: createId(),
              label: "Somewhat disappointed",
            },
            {
              id: createId(),
              label: "Very disappointed",
            },
          ],
        },
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "What is your role?",
          subheader: "Please select one of the following options:",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Founder",
            },
            {
              id: createId(),
              label: "Executive",
            },
            {
              id: createId(),
              label: "Product Manager",
            },
            {
              id: createId(),
              label: "Product Owner",
            },
            {
              id: createId(),
              label: "Software Engineer",
            },
          ],
        },
        {
          id: createId(),
          type: "openText",
          headline: "What type of people do you think would most benefit from {{productName}}?",
          required: true,
        },
        {
          id: createId(),
          type: "openText",
          headline: "What is the main benefit your receive from {{productName}}?",
          required: true,
        },
        {
          id: createId(),
          type: "openText",
          headline: "How can we improve {{productName}} for you?",
          subheader: "Please be as specific as possible.",
          required: true,
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Onboarding Segmentation",
    icon: OnboardingIcon,
    category: "Product Experience",
    objectives: ["increase_user_adoption", "improve_user_retention"],
    description: "Learn more about who signed up to your product and why.",
    preset: {
      name: "Onboarding Segmentation",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "What is your role?",
          subheader: "Please select one of the following options:",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Founder",
            },
            {
              id: createId(),
              label: "Executive",
            },
            {
              id: createId(),
              label: "Product Manager",
            },
            {
              id: createId(),
              label: "Product Owner",
            },
            {
              id: createId(),
              label: "Software Engineer",
            },
          ],
        },
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "What's your company size?",
          subheader: "Please select one of the following options:",
          required: true,
          choices: [
            {
              id: createId(),
              label: "only me",
            },
            {
              id: createId(),
              label: "1-5 employees",
            },
            {
              id: createId(),
              label: "6-10 employees",
            },
            {
              id: createId(),
              label: "11-100 employees",
            },
            {
              id: createId(),
              label: "over 100 employees",
            },
          ],
        },
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "How did you hear about us first?",
          subheader: "Please select one of the following options:",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Recommendation",
            },
            {
              id: createId(),
              label: "Social Media",
            },
            {
              id: createId(),
              label: "Ads",
            },
            {
              id: createId(),
              label: "Google Search",
            },
            {
              id: createId(),
              label: "In a Podcast",
            },
          ],
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Uncover Strengths & Weaknesses",
    icon: TaskListSearchIcon,
    category: "Growth",
    objectives: ["sharpen_marketing_messaging", "improve_user_retention"],
    description: "Find out what users like and don't like about your product or offering.",
    preset: {
      name: "Uncover Strengths & Weaknesses",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "What do you value most about our service?",
          subheader: "Please select one of the following options:",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Ease of use",
            },
            {
              id: createId(),
              label: "Good value for money",
            },
            {
              id: createId(),
              label: "It's open-source",
            },
            {
              id: createId(),
              label: "The founders are pretty",
            },
          ],
        },
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "What should we improve on?",
          subheader: "Please select one of the following options:",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Documentation",
            },
            {
              id: createId(),
              label: "Customizability",
            },
            {
              id: createId(),
              label: "Pricing",
            },
            {
              id: createId(),
              label: "Humbleness of founders",
            },
          ],
        },
        {
          id: createId(),
          type: "openText",
          headline: "Would you like to add something?",
          subheader: "Feel free to speak your mind, we do too.",
          required: false,
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Marketing Attribution",
    icon: AppPieChartIcon,
    category: "Growth",
    objectives: ["increase_conversion", "sharpen_marketing_messaging"],
    description: "How did you first hear about us?",
    preset: {
      name: "Marketing Attribution",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "How did you hear about us first?",
          subheader: "Please select one of the following options:",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Recommendation",
            },
            {
              id: createId(),
              label: "Social Media",
            },
            {
              id: createId(),
              label: "Ads",
            },
            {
              id: createId(),
              label: "Google Search",
            },
            {
              id: createId(),
              label: "In a Podcast",
            },
          ],
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Churn Survey",
    icon: CancelSubscriptionIcon,
    category: "Increase Revenue",
    objectives: ["sharpen_marketing_messaging", "improve_user_retention"],
    description: "Find out why people cancel their subscriptions. These insights are pure gold!",
    preset: {
      name: "Churn Survey",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          logic: [
            { value: "Difficult to use", condition: "equals", destination: "sxwpskjgzzpmkgfxzi15inif" },
            { value: "It's too expensive", condition: "equals", destination: "mao94214zoo6c1at5rpuz7io" },
            {
              value: "I am missing features",
              condition: "equals",
              destination: "l054desub14syoie7n202vq4",
            },
            {
              value: "Poor customer service",
              condition: "equals",
              destination: "hdftsos1odzjllr7flj4m3j9",
            },
            { value: "I just didn't need it anymore", condition: "equals", destination: "end" },
          ],
          choices: [
            { id: createId(), label: "Difficult to use" },
            { id: createId(), label: "It's too expensive" },
            { id: createId(), label: "I am missing features" },
            { id: createId(), label: "Poor customer service" },
            { id: createId(), label: "I just didn't need it anymore" },
          ],
          headline: "Why did you cancel your subscription?",
          required: true,
          subheader: "We're sorry to see you leave. Help us do better:",
        },
        {
          id: "sxwpskjgzzpmkgfxzi15inif",
          type: "openText",
          logic: [{ condition: "submitted", destination: "end" }],
          headline: "What would have made {{productName}} easier to use?",
          required: true,
          subheader: "",
          buttonLabel: "Send",
        },
        {
          id: "mao94214zoo6c1at5rpuz7io",
          html: '<p class="fb-editor-paragraph" dir="ltr"><span>We\'d love to keep you as a customer. Happy to offer a 30% discount for the next year.</span></p>',
          type: "cta",
          logic: [{ condition: "submitted", destination: "end" }],
          headline: "Get 30% off for the next year!",
          required: true,
          buttonUrl: "https://formbricks.com",
          buttonLabel: "Get 30% off",
          buttonExternal: true,
          dismissButtonLabel: "Skip",
        },
        {
          id: "l054desub14syoie7n202vq4",
          type: "openText",
          logic: [{ condition: "submitted", destination: "end" }],
          headline: "What features are you missing?",
          required: true,
          subheader: "",
        },
        {
          id: "hdftsos1odzjllr7flj4m3j9",
          html: '<p class="fb-editor-paragraph" dir="ltr"><span>We aim to provide the best possible customer service. Please email our CEO and she will personally handle your issue.</span></p>',
          type: "cta",
          logic: [{ condition: "submitted", destination: "end" }],
          headline: "So sorry to hear 😔 Talk to our CEO directly!",
          required: true,
          buttonUrl: "mailto:ceo@company.com",
          buttonLabel: "Send email to CEO",
          buttonExternal: true,
          dismissButtonLabel: "Skip",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Improve Trial Conversion",
    icon: BaseballIcon,
    category: "Increase Revenue",
    objectives: ["increase_user_adoption", "increase_conversion", "improve_user_retention"],
    description: "Find out why people stopped their trial. These insights help you improve your funnel.",
    preset: {
      name: "Improve Trial Conversion",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          logic: [
            {
              value: "I didn't get much value out of it",
              condition: "equals",
              destination: "aew2ymg51mffnt9db7duz9t3",
            },
            {
              value: "I expected something else",
              condition: "equals",
              destination: "rnrfydttavtsf2t2nfx1df7m",
            },
            {
              value: "It's too expensive for what it does",
              condition: "equals",
              destination: "x760wga1fhtr1i80cpssr7af",
            },
            {
              value: "I am missing a feature",
              condition: "equals",
              destination: "rbhww1pix03r6sl4xc511wqg",
            },
            { value: "I was just looking around", condition: "equals", destination: "end" },
          ],
          choices: [
            { id: createId(), label: "I didn't get much value out of it" },
            { id: createId(), label: "I expected something else" },
            { id: createId(), label: "It's too expensive for what it does" },
            { id: createId(), label: "I am missing a feature" },
            { id: createId(), label: "I was just looking around" },
          ],
          headline: "Why did you stop your trial?",
          required: true,
          subheader: "Help us understand you better:",
        },
        {
          id: "aew2ymg51mffnt9db7duz9t3",
          type: "openText",
          logic: [{ condition: "submitted", destination: "bqiyml1ym74ggx6htwdo7rlu" }],
          headline: "Sorry to hear. What was the biggest problem using {{productName}}?",
          required: true,
          buttonLabel: "Next",
        },
        {
          id: "rnrfydttavtsf2t2nfx1df7m",
          type: "openText",
          logic: [{ condition: "submitted", destination: "bqiyml1ym74ggx6htwdo7rlu" }],
          headline: "What did you expect {{productName}} would do for you?",
          required: true,
          buttonLabel: "Next",
        },
        {
          id: "x760wga1fhtr1i80cpssr7af",
          html: '<p class="fb-editor-paragraph" dir="ltr"><span>We\'re happy to offer you a 20% discount on a yearly plan.</span></p>',
          type: "cta",
          logic: [{ condition: "submitted", destination: "end" }],
          headline: "Sorry to hear! Get 20% off the first year.",
          required: true,
          buttonUrl: "https://formbricks.com/github",
          buttonLabel: "Get 20% off",
          buttonExternal: true,
          dismissButtonLabel: "Skip",
        },
        {
          id: "rbhww1pix03r6sl4xc511wqg",
          type: "openText",
          logic: [{ condition: "submitted", destination: "bqiyml1ym74ggx6htwdo7rlu" }],
          headline: "Which features are you missing?",
          required: true,
          subheader: "What would you like to achieve?",
          buttonLabel: "Next",
        },
        {
          id: "bqiyml1ym74ggx6htwdo7rlu",
          type: "openText",
          logic: [
            { condition: "submitted", destination: "end" },
            { condition: "skipped", destination: "end" },
          ],
          headline: "How are you solving your problem now?",
          required: false,
          subheader: "Please name alternative solutions:",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Changing subscription experience",
    icon: CashCalculatorIcon,
    category: "Increase Revenue",
    objectives: ["increase_conversion", "improve_user_retention"],
    description: "Find out what goes through peoples minds when changing their subscriptions.",
    preset: {
      name: "Changing subscription experience",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "How easy was it to change your plan?",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Extremely difficult",
            },
            {
              id: createId(),
              label: "It took a while, but I got it",
            },
            {
              id: createId(),
              label: "It was alright",
            },
            {
              id: createId(),
              label: "Quite easy",
            },
            {
              id: createId(),
              label: "Very easy, love it!",
            },
          ],
        },
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "Is the pricing information easy to understand?",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Yes, very clear.",
            },
            {
              id: createId(),
              label: "I was confused at first, but found what I needed.",
            },
            {
              id: createId(),
              label: "Quite complicated.",
            },
          ],
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Measure Task Accomplishment",
    icon: CheckMarkIcon,
    category: "Product Experience",
    objectives: ["increase_user_adoption", "improve_user_retention"],
    description: "See if people get their 'Job To Be Done' done. Successful people are better customers.",
    preset: {
      name: "Measure Task Accomplishment",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          logic: [
            { value: "Working on it, boss", condition: "equals", destination: "nq88udm0jjtylr16ax87xlyc" },
            { value: "Yes", condition: "equals", destination: "rjeac33gd13h3nnbrbid1fb2" },
            { value: "No", condition: "equals", destination: "u83zhr66knyfozccoqojx7bc" },
          ],
          choices: [
            { id: createId(), label: "Yes" },
            { id: createId(), label: "Working on it, boss" },
            { id: createId(), label: "No" },
          ],
          headline: "Were you able to accomplish what you came here to do today?",
          required: true,
        },
        {
          id: "rjeac33gd13h3nnbrbid1fb2",
          type: "rating",
          logic: [{ value: 4, condition: "greaterEqual", destination: "nq88udm0jjtylr16ax87xlyc" }],
          range: 5,
          scale: "number",
          headline: "How easy was it to achieve your goal?",
          required: true,
          lowerLabel: "Very difficult",
          upperLabel: "Very easy",
        },
        {
          id: "s0999bhpaz8vgf7ps264piek",
          type: "openText",
          logic: [
            { condition: "submitted", destination: "end" },
            { condition: "skipped", destination: "end" },
          ],
          headline: "What made it hard?",
          required: false,
          placeholder: "Type your answer here...",
        },
        {
          id: "nq88udm0jjtylr16ax87xlyc",
          type: "openText",
          logic: [
            { condition: "skipped", destination: "end" },
            { condition: "submitted", destination: "end" },
          ],
          headline: "Great! What did you come here to do today?",
          required: false,
          buttonLabel: "Send",
        },
        {
          id: "u83zhr66knyfozccoqojx7bc",
          type: "openText",
          headline: "What stopped you?",
          required: true,
          buttonLabel: "Send",
          placeholder: "Type your answer here...",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Identify Customer Goals",
    icon: ArrowRightCircleIcon,
    category: "Product Experience",
    objectives: ["increase_user_adoption", "sharpen_marketing_messaging", "improve_user_retention"],
    description:
      "Better understand if your messaging creates the right expectations of the value your product provides.",
    preset: {
      name: "Identify Customer Goals",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "What's your primary goal for using {{productName}}?",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Understand my user base deeply",
            },
            {
              id: createId(),
              label: "Identify upselling opportunities",
            },
            {
              id: createId(),
              label: "Build the best possible product",
            },
            {
              id: createId(),
              label: "Rule the world to make everyone breakfast brussels sprouts.",
            },
          ],
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Feature Chaser",
    icon: DogChaserIcon,
    category: "Product Experience",
    objectives: ["improve_user_retention"],
    description: "Follow up with users who just used a specific feature.",
    preset: {
      name: "Feature Chaser",
      questions: [
        {
          id: createId(),
          type: "rating",
          range: 5,
          scale: "number",
          headline: "How important is [ADD FEATURE] for you?",
          required: true,
          lowerLabel: "Not important",
          upperLabel: "Very important",
        },
        {
          id: createId(),
          type: "multipleChoiceSingle",
          choices: [
            { id: createId(), label: "Aspect 1" },
            { id: createId(), label: "Aspect 2" },
            { id: createId(), label: "Aspect 3" },
            { id: createId(), label: "Aspect 4" },
          ],
          headline: "Which aspect is most important?",
          required: true,
          subheader: "",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Fake Door Follow-Up",
    icon: DoorIcon,
    category: "Exploration",
    objectives: ["increase_user_adoption"],
    description: "Follow up with users who ran into one of your Fake Door experiments.",
    preset: {
      name: "Fake Door Follow-Up",
      questions: [
        {
          id: createId(),
          type: "rating",
          headline: "How important is this feature for you?",
          required: true,
          lowerLabel: "Not important",
          upperLabel: "Very important",
          range: 5,
          scale: "number",
        },
        {
          id: createId(),
          type: "multipleChoiceMulti",
          headline: "What should be definitely include building this?",
          required: false,
          choices: [
            {
              id: createId(),
              label: "Aspect 1",
            },
            {
              id: createId(),
              label: "Aspect 2",
            },
            {
              id: createId(),
              label: "Aspect 3",
            },
            {
              id: createId(),
              label: "Aspect 4",
            },
          ],
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Feedback Box",
    icon: FeedbackIcon,
    category: "Product Experience",
    objectives: ["improve_user_retention"],
    description: "Give your users the chance to seamlessly share what's on their minds.",
    preset: {
      name: "Feedback Box",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          logic: [
            { value: "Bug report 🐞", condition: "equals", destination: "dnbiuq4l33l7jypcf2cg6vhh" },
            { value: "Feature Request 💡", condition: "equals", destination: "en9nuuevbf7g9oa9rzcs1l50" },
          ],
          choices: [
            { id: createId(), label: "Bug report 🐞" },
            { id: createId(), label: "Feature Request 💡" },
          ],
          headline: "What's on your mind, boss?",
          required: true,
          subheader: "Thanks for sharing. We'll get back to you asap.",
        },
        {
          id: "dnbiuq4l33l7jypcf2cg6vhh",
          type: "openText",
          logic: [{ condition: "submitted", destination: "a6c76m5oocw6xp9agf3d2tam" }],
          headline: "What's broken?",
          required: true,
          subheader: "The more detail, the better :)",
        },
        {
          id: "a6c76m5oocw6xp9agf3d2tam",
          html: '<p class="fb-editor-paragraph" dir="ltr"><span>We will fix this as soon as possible. Do you want to be notified when we did?</span></p>',
          type: "cta",
          logic: [
            { condition: "submitted", destination: "end" },
            { condition: "skipped", destination: "end" },
          ],
          headline: "Want to stay in the loop?",
          required: false,
          buttonLabel: "Yes, notify me",
          buttonExternal: false,
          dismissButtonLabel: "No, thanks",
        },
        {
          id: "en9nuuevbf7g9oa9rzcs1l50",
          type: "openText",
          headline: "Lovely, tell us more!",
          required: true,
          subheader: "What problem do you want us to solve?",
          buttonLabel: "Request feature",
          placeholder: "Type your answer here...",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Integration Setup Survey",
    icon: DashboardIcon,
    category: "Product Experience",
    objectives: ["increase_user_adoption"],
    description: "Evaluate how easily users can add integrations to your product. Find blind spots.",
    preset: {
      name: "Integration Usage Survey",
      questions: [
        {
          id: "s6ss6znzxdwjod1hv16fow4w",
          type: "rating",
          logic: [{ value: 4, condition: "greaterEqual", destination: "ef0qo3l8iisd517ikp078u1p" }],
          range: 5,
          scale: "number",
          headline: "How easy was it to set this integration up?",
          required: true,
          subheader: "",
          lowerLabel: "Not easy",
          upperLabel: "Very easy",
        },
        {
          id: "mko13ptjj6tpi5u2pl7a5drz",
          type: "openText",
          headline: "Why was it hard?",
          required: false,
          placeholder: "Type your answer here...",
        },
        {
          id: "ef0qo3l8iisd517ikp078u1p",
          type: "openText",
          headline: "What other tools would you like to use with {{productName}}?",
          required: false,
          subheader: "We keep building integrations, yours can be next:",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "New Integration Survey",
    icon: DashboardIcon,
    category: "Exploration",
    objectives: ["increase_user_adoption", "increase_conversion"],
    description: "Find out which integrations your users would like to see next.",
    preset: {
      name: "New integration survey",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "Which other tools are you using?",
          required: true,
          choices: [
            {
              id: createId(),
              label: "PostHog",
            },
            {
              id: createId(),
              label: "Segment",
            },
            {
              id: createId(),
              label: "Hubspot",
            },
            {
              id: createId(),
              label: "Twilio",
            },
            {
              id: createId(),
              label: "Other",
            },
          ],
        },
        {
          id: createId(),
          type: "openText",
          headline: "If you chose other, please clarify:",
          required: false,
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Docs Feedback",
    icon: CodeBookIcon,
    category: "Product Experience",
    objectives: ["increase_user_adoption", "improve_user_retention"],
    description: "Measure how clear each page of your developer documentation is.",
    preset: {
      name: "{{productName}} Docs Feedback",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "Was this page helpful?",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Yes 👍",
            },
            {
              id: createId(),
              label: "No 👎",
            },
          ],
        },
        {
          id: createId(),
          type: "openText",
          headline: "Please elaborate:",
          required: false,
        },
        {
          id: createId(),
          type: "openText",
          headline: "Page URL",
          required: false,
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Interview Prompt",
    icon: InterviewPromptIcon,
    category: "Exploration",
    objectives: ["improve_user_retention"],
    description: "Invite a specific subset of your users to schedule an interview with your product team.",
    preset: {
      name: "Interview Prompt",
      questions: [
        {
          id: createId(),
          type: "cta",
          headline: "Do you have 15 min to talk to us? 🙏",
          html: "You're one of our power users. We would love to interview you briefly!",
          buttonLabel: "Book slot",
          buttonUrl: "https://cal.com/johannes",
          buttonExternal: true,
          required: false,
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Review Prompt",
    icon: HeartCommentIcon,
    category: "Growth",
    objectives: ["support_sales"],
    description: "Invite users who love your product to review it publicly.",
    preset: {
      name: "Review Prompt",
      questions: [
        {
          id: createId(),
          type: "rating",
          logic: [{ value: 3, condition: "lessEqual", destination: "tk9wpw2gxgb8fa6pbpp3qq5l" }],
          range: 5,
          scale: "star",
          headline: "How do you like {{productName}}?",
          required: true,
          subheader: "",
          lowerLabel: "",
          upperLabel: "",
        },
        {
          id: createId(),
          html: '<p class="fb-editor-paragraph" dir="ltr"><span>This helps us a lot.</span></p>',
          type: "cta",
          logic: [{ condition: "submitted", destination: "end" }],
          headline: "Happy to hear 🙏 Please write a review for us!",
          required: true,
          buttonUrl: "https://formbricks.com/github",
          buttonLabel: "Write review",
          buttonExternal: true,
        },
        {
          id: "tk9wpw2gxgb8fa6pbpp3qq5l",
          type: "openText",
          headline: "Sorry to hear! What is ONE thing we can do better?",
          required: true,
          subheader: "Help us improve your experience.",
          buttonLabel: "Send",
          placeholder: "Type your answer here...",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Net Promoter Score (NPS)",
    icon: GaugeSpeedFastIcon,
    category: "Customer Success",
    objectives: ["support_sales"],
    description: "Measure the Net Promoter Score of your product.",
    preset: {
      name: "{{productName}} NPS",
      questions: [
        {
          id: createId(),
          type: "nps",
          headline: "How likely are you to recommend {{productName}} to a friend or colleague?",
          required: false,
          lowerLabel: "Not likely",
          upperLabel: "Very likely",
        },
        {
          id: createId(),
          type: "openText",
          headline: "What made you give that rating?",
          required: false,
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Customer Satisfaction Score (CSAT)",
    icon: GaugeSpeedFastIcon,
    category: "Customer Success",
    objectives: ["support_sales"],
    description: "Measure the Customer Satisfaction Score of your product.",
    preset: {
      name: "{{productName}} CSAT",
      questions: [
        {
          id: createId(),
          type: "rating",
          logic: [{ value: 3, condition: "lessEqual", destination: "vyo4mkw4ln95ts4ya7qp2tth" }],
          range: 5,
          scale: "smiley",
          headline: "How satisfied are you with your {{productName}} experience?",
          required: true,
          subheader: "",
          lowerLabel: "Not satisfied",
          upperLabel: "Very satisfied",
        },
        {
          id: createId(),
          type: "openText",
          logic: [{ condition: "submitted", destination: "end" }],
          headline: "Lovely! Is there anything we can do to improve your experience?",
          required: false,
          placeholder: "Type your answer here...",
        },
        {
          id: "vyo4mkw4ln95ts4ya7qp2tth",
          type: "openText",
          headline: "Ugh, sorry! Is there anything we can do to improve your experience?",
          required: false,
          placeholder: "Type your answer here...",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Identify upsell opportunities",
    icon: ArrowUpRightIcon,
    category: "Increase Revenue",
    objectives: ["support_sales", "sharpen_marketing_messaging"],
    description: "Find out how much time your product saves your user. Use it to upsell.",
    preset: {
      name: "Identify upsell opportunities",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "How many hours does your team save per week by using {{productName}}?",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Less than 1 hour",
            },
            {
              id: createId(),
              label: "1 to 2 hours",
            },
            {
              id: createId(),
              label: "3 to 5 hours",
            },
            {
              id: createId(),
              label: "5+ hours",
            },
          ],
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Build Product Roadmap",
    icon: LoadingBarIcon,
    category: "Product Experience",
    objectives: ["increase_user_adoption", "improve_user_retention"],
    description: "Ask how users rate your product. Identify blind spots to build your roadmap.",
    preset: {
      name: "Build Product Roadmap",
      questions: [
        {
          id: createId(),
          type: "rating",
          headline: "How satisfied are you with the features of {{productName}}?",
          required: true,
          lowerLabel: "Not satisfied",
          upperLabel: "Very satisfied",
          scale: "number",
          range: 5,
        },
        {
          id: createId(),
          type: "openText",
          headline: "What's the #1 thing you'd like to change in {{productName}}?",
          required: false,
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Gauge Feature Satisfaction",
    icon: UserSearchGlasIcon,
    category: "Product Experience",
    objectives: ["increase_user_adoption", "improve_user_retention"],
    description: "Evaluate the satisfaction of specific features of your product.",
    preset: {
      name: "Gauge Feature Satisfaction",
      questions: [
        {
          id: createId(),
          type: "rating",
          headline: "How easy was it to achieve ... ?",
          required: true,
          lowerLabel: "Not easy",
          upperLabel: "Very easy",
          scale: "number",
          range: 5,
        },
        {
          id: createId(),
          type: "openText",
          headline: "What is one thing we could do better?",
          required: false,
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Marketing Site Clarity",
    icon: VideoTabletAdjustIcon,
    category: "Growth",
    objectives: ["increase_conversion", "sharpen_marketing_messaging"],
    description: "Identify users dropping off your marketing site. Improve your messaging.",
    preset: {
      name: "Marketing Site Clarity",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          headline: "Do you have all the info you need to give {{productName}} a try?",
          required: true,
          choices: [
            {
              id: createId(),
              label: "Yes, totally",
            },
            {
              id: createId(),
              label: "Kind of...",
            },
            {
              id: createId(),
              label: "No, not at all",
            },
          ],
        },
        {
          id: createId(),
          type: "openText",
          headline: "What’s missing or unclear to you about {{productName}}?",
          required: false,
        },
        {
          id: createId(),
          type: "cta",
          headline: "Thanks for your answer! Get 25% off your first 6 months:",
          required: false,
          buttonLabel: "Get discount",
          buttonUrl: "https://app.formbricks.com/auth/signup",
          buttonExternal: true,
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Customer Effort Score (CES)",
    icon: GaugeSpeedFastIcon,
    category: "Product Experience",
    objectives: ["increase_user_adoption", "improve_user_retention"],
    description: "Determine how easy it is to use a feature.",
    preset: {
      name: "Customer Effort Score (CES)",
      questions: [
        {
          id: createId(),
          type: "rating",
          range: 5,
          scale: "number",
          headline: "{{productName}} makes it easy for me to [ADD GOAL]",
          required: true,
          subheader: "",
          lowerLabel: "Disagree strongly",
          upperLabel: "Agree strongly",
        },
        {
          id: createId(),
          type: "openText",
          headline: "Thanks! How could we make it easier for you to [ADD GOAL]?",
          required: true,
          placeholder: "Type your answer here...",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Earned Advocacy Score (EAS)",
    icon: GaugeSpeedFastIcon,
    category: "Growth",
    objectives: ["support_sales", "sharpen_marketing_messaging"],
    description:
      "The EAS is a riff off the NPS but asking for actual past behaviour instead of lofty intentions.",
    preset: {
      name: "Earned Advocacy Score (EAS)",
      questions: [
        {
          id: createId(),
          type: "multipleChoiceSingle",
          logic: [{ value: "No", condition: "equals", destination: "duz2qp8eftix9wty1l221x1h" }],
          choices: [
            { id: createId(), label: "Yes" },
            { id: createId(), label: "No" },
          ],
          headline: "Have you actively recommended {{productName}} to others?",
          required: true,
          subheader: "",
        },
        {
          id: createId(),
          type: "openText",
          logic: [{ condition: "submitted", destination: "yhfew1j3ng6luy7t7qynwj79" }],
          headline: "Great to hear! Why did you recommend us?",
          required: true,
          placeholder: "Type your answer here...",
        },
        {
          id: "duz2qp8eftix9wty1l221x1h",
          type: "openText",
          headline: "So sad. Why not?",
          required: true,
          placeholder: "Type your answer here...",
        },
        {
          id: "yhfew1j3ng6luy7t7qynwj79",
          type: "multipleChoiceSingle",
          logic: [{ value: "No", condition: "equals", destination: "end" }],
          choices: [
            { id: createId(), label: "Yes" },
            { id: createId(), label: "No" },
          ],
          headline: "Have you actively discouraged others from choosing {{produtName}}?",
          required: true,
          subheader: "",
        },
        {
          id: createId(),
          type: "openText",
          headline: "What made you discourage them?",
          required: true,
          placeholder: "Type your answer here...",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Rate Checkout Experience",
    icon: GaugeSpeedFastIcon,
    category: "Increase Revenue",
    objectives: ["increase_conversion"],
    description: "Let customers rate the checkout experience to tweak conversion.",
    preset: {
      name: "Rate Checkout Experience",
      questions: [
        {
          id: createId(),
          type: "rating",
          logic: [{ value: 4, condition: "greaterEqual", destination: "lpof3d9t9hmnqvyjlpksmxd7" }],
          range: 5,
          scale: "number",
          headline: "How easy or difficult was it to complete the checkout?",
          required: true,
          subheader: "",
          lowerLabel: "Very difficult",
          upperLabel: "Very easy",
        },
        {
          id: createId(),
          type: "openText",
          logic: [{ condition: "submitted", destination: "end" }],
          headline: "Sorry about that! What would have made it easier for you?",
          required: true,
          placeholder: "Type your answer here...",
        },
        {
          id: "lpof3d9t9hmnqvyjlpksmxd7",
          type: "openText",
          headline: "Lovely! Is there anything we can do to improve your experience?",
          required: true,
          placeholder: "Type your answer here...",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Measure Search Experience",
    icon: GaugeSpeedFastIcon,
    category: "Product Experience",
    objectives: ["improve_user_retention"],
    description: "Measure how relevant your search results are.",
    preset: {
      name: "Measure Search Experience",
      questions: [
        {
          id: createId(),
          type: "rating",
          logic: [{ value: 4, condition: "greaterEqual", destination: "adcs3d9t9hmnqvyjlpksmxd7" }],
          range: 5,
          scale: "number",
          headline: "How relevant are these search results?",
          required: true,
          subheader: "",
          lowerLabel: "Not at all relevant",
          upperLabel: "Very relevant",
        },
        {
          id: createId(),
          type: "openText",
          logic: [{ condition: "submitted", destination: "end" }],
          headline: "Ugh! What makes the results irrelevant for you?",
          required: true,
          placeholder: "Type your answer here...",
        },
        {
          id: "adcs3d9t9hmnqvyjlpksmxd7",
          type: "openText",
          headline: "Lovely! Is there anything we can do to improve your experience?",
          required: true,
          placeholder: "Type your answer here...",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Evaluate Content Quality",
    icon: GaugeSpeedFastIcon,
    category: "Growth",
    objectives: ["increase_conversion"],
    description: "Measure if your content marketing pieces hit right.",
    preset: {
      name: "Evaluate Content Quality",
      questions: [
        {
          id: createId(),
          type: "rating",
          logic: [{ value: 4, condition: "greaterEqual", destination: "adcs3d9t9hmnqvyjlpkswi38" }],
          range: 5,
          scale: "number",
          headline: "How well did this article address what you were hoping to learn?",
          required: true,
          subheader: "",
          lowerLabel: "Not at all well",
          upperLabel: "Extremely well",
        },
        {
          id: createId(),
          type: "openText",
          logic: [{ condition: "submitted", destination: "end" }],
          headline: "Hmpft! What were you hoping for?",
          required: true,
          placeholder: "Type your answer here...",
        },
        {
          id: "adcs3d9t9hmnqvyjlpkswi38",
          type: "openText",
          headline: "Lovely! Is there anything else you would like us to cover?",
          required: true,
          placeholder: "Topics, trends, tutorials...",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  {
    name: "Identify Sign Up Barriers",
    icon: GaugeSpeedFastIcon,
    category: "Growth",
    objectives: ["increase_conversion"],
    description: "Offer a discount to gather insights about sign up barriers.",
    preset: {
      name: "{{productName}} Sign Up Barriers",
      questions: [
        {
          id: createId(),
          html: '<p class="fb-editor-paragraph" dir="ltr"><span>You seem to be considering signing up. Answer four questions and get 10% on any plan.</span></p>',
          type: "cta",
          logic: [{ condition: "skipped", destination: "end" }],
          headline: "Answer this short survey, get 10% off!",
          required: false,
          buttonLabel: "Get 10% discount",
          buttonExternal: false,
          dismissButtonLabel: "No, thanks",
        },
        {
          id: createId(),
          type: "rating",
          logic: [{ value: "5", condition: "equals", destination: "end" }],
          range: 5,
          scale: "number",
          headline: "How likely are you to sign up for {{productName}}?",
          required: true,
          subheader: "",
          lowerLabel: "Not at all likely",
          upperLabel: "Very likely",
        },
        {
          id: createId(),
          type: "multipleChoiceSingle",
          logic: [
            {
              value: "May not have what I'm looking for",
              condition: "equals",
              destination: "atiw0j1oykb77zr0b7q4tixu",
            },
            {
              value: "Still comparing options",
              condition: "equals",
              destination: "j7jkpolm5xl7u0zt3g0e4z7d",
            },
            { value: "Seems complicated", condition: "equals", destination: "t5gvag2d7kq311szz5iyiy79" },
            { value: "Pricing is a concern", condition: "equals", destination: "or0yhhrof753sq9ug4mdavgz" },
            { value: "Something else", condition: "equals", destination: "v0pq1qcnm6ohiry5ywcd91qq" },
          ],
          choices: [
            { id: createId(), label: "May not have what I'm looking for" },
            { id: createId(), label: "Still comparing options" },
            { id: createId(), label: "Seems complicated" },
            { id: createId(), label: "Pricing is a concern" },
            { id: createId(), label: "Something else" },
          ],
          headline: "What is holding you back from trying {{productName}}?",
          required: true,
          subheader: "",
        },
        {
          id: "atiw0j1oykb77zr0b7q4tixu",
          type: "openText",
          logic: [{ condition: "submitted", destination: "k3q0vt1ko0bzbsq076p7lnys" }],
          headline: "What do you need but {{productName}} does not offer?",
          required: true,
          placeholder: "Type your answer here...",
        },
        {
          id: "j7jkpolm5xl7u0zt3g0e4z7d",
          type: "openText",
          logic: [{ condition: "submitted", destination: "k3q0vt1ko0bzbsq076p7lnys" }],
          headline: "What options are you looking at?",
          required: true,
          placeholder: "Type your answer here...",
        },
        {
          id: "t5gvag2d7kq311szz5iyiy79",
          type: "openText",
          logic: [{ condition: "submitted", destination: "k3q0vt1ko0bzbsq076p7lnys" }],
          headline: "What seems complicated to you?",
          required: true,
          placeholder: "Type your answer here...",
        },
        {
          id: "or0yhhrof753sq9ug4mdavgz",
          type: "openText",
          logic: [{ condition: "submitted", destination: "k3q0vt1ko0bzbsq076p7lnys" }],
          headline: "What are you concerned about regarding pricing?",
          required: true,
          placeholder: "Type your answer here...",
        },
        {
          id: "v0pq1qcnm6ohiry5ywcd91qq",
          type: "openText",
          logic: [{ condition: "submitted", destination: "k3q0vt1ko0bzbsq076p7lnys" }],
          headline: "Please explain:",
          required: true,
          placeholder: "Type your answer here...",
        },
        {
          id: "k3q0vt1ko0bzbsq076p7lnys",
          html: '<p class="fb-editor-paragraph" dir="ltr"><span>Thanks a lot for taking the time to share feedback 🙏</span></p>',
          type: "cta",
          headline: "Thanks! Here is your code: SIGNUPNOW10",
          required: false,
          buttonUrl: "https://app.formbricks.com/auth/signup",
          buttonLabel: "Sign Up",
          buttonExternal: true,
          dismissButtonLabel: "Skip for now",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },
  /* {
    name: "TEMPLATE MASTER",
    icon: GaugeSpeedFastIcon,
    category: "X",
    objectives: ["X"],
    description: "X",
    preset: {
      name: "X",
      questions: [
        {
          id: createId(),
          type: "X",
          headline: "X",
          required: false,
          lowerLabel: "Not likely",
          upperLabel: "Very likely",
        },
      ],
      thankYouCard: thankYouCardDefault,
    },
  },  */
];

export const customSurvey: Template = {
  name: "Start from scratch",
  description: "Create a survey without template.",
  icon: null,
  preset: {
    name: "New Survey",
    questions: [
      {
        id: createId(),
        type: "openText",
        headline: "Custom Survey",
        subheader: "This is an example survey.",
        placeholder: "Type your answer here...",
        required: true,
      },
    ],
    thankYouCard: thankYouCardDefault,
  },
};
